(function(c,l,n){"function"===typeof define&&define.amd?define(["jquery"],c):"object"===typeof exports?module.exports=c(require("jquery")):c(l||n)})(function(c){var l=function(b,d,a){var e={invalid:[],getCaret:function(){try{var d,a=0,c=b.get(0),f=document.selection,g=c.selectionStart;if(f&&-1===navigator.appVersion.indexOf("MSIE 10"))d=f.createRange(),d.moveStart("character",-e.val().length),a=d.text.length;else if(g||"0"===g)a=g;return a}catch(h){}},setCaret:function(d){try{if(b.is(":focus")){var a,
c=b.get(0);c.setSelectionRange?c.setSelectionRange(d,d):(a=c.createTextRange(),a.collapse(!0),a.moveEnd("character",d),a.moveStart("character",d),a.select())}}catch(f){}},events:function(){b.on("keydown.mask",function(d){b.data("mask-keycode",d.keyCode||d.which);b.data("mask-previus-value",b.val());b.data("mask-previus-caret-pos",e.getCaret());e.maskDigitPosMapOld=e.maskDigitPosMap}).on(c.jMaskGlobals.useInput?"input.mask":"keyup.mask",e.behaviour).on("paste.mask drop.mask",function(){setTimeout(function(){b.keydown().keyup()},
100)}).on("change.mask",function(){b.data("changed",!0)}).on("blur.mask",function(){h===e.val()||b.data("changed")||b.trigger("change");b.data("changed",!1)}).on("blur.mask",function(){h=e.val()}).on("focus.mask",function(b){!0===a.selectOnFocus&&c(b.target).select()}).on("focusout.mask",function(){a.clearIfNotMatch&&!k.test(e.val())&&e.val("")})},getRegexMask:function(){for(var b=[],a,c,f,e,h=0;h<d.length;h++)(a=g.translation[d.charAt(h)])?(c=a.pattern.toString().replace(/.{1}$|^.{1}/g,""),f=a.optional,
(a=a.recursive)?(b.push(d.charAt(h)),e={digit:d.charAt(h),pattern:c}):b.push(f||a?c+"?":c)):b.push(d.charAt(h).replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"));b=b.join("");e&&(b=b.replace(new RegExp("("+e.digit+"(.*"+e.digit+")?)"),"($1)?").replace(new RegExp(e.digit,"g"),e.pattern));return new RegExp(b)},destroyEvents:function(){b.off("input keydown keyup paste drop blur focusout ".split(" ").join(".mask "))},val:function(d){var a=b.is("input")?"val":"text";if(0<arguments.length){if(b[a]()!==d)b[a](d);
a=b}else a=b[a]();return a},calculateCaretPosition:function(){var d=b.data("mask-previus-value")||"",a=e.getMasked(),c=e.getCaret();if(d!==a){for(var f=b.data("mask-previus-caret-pos")||0,a=a.length,g=d.length,h=d=0,k=0,u=0,p=0,p=c;p<a&&e.maskDigitPosMap[p];p++)h++;for(p=c-1;0<=p&&e.maskDigitPosMap[p];p--)d++;for(p=c-1;0<=p;p--)e.maskDigitPosMap[p]&&k++;for(p=f-1;0<=p;p--)e.maskDigitPosMapOld[p]&&u++;c>g?c=10*a:f>=c&&f!==g?e.maskDigitPosMapOld[c]||(f=c,c=c-(u-k)-d,e.maskDigitPosMap[c]&&(c=f)):c>f&&
(c+=k-u,c+=h)}return c},behaviour:function(d){d=d||window.event;e.invalid=[];var a=b.data("mask-keycode");if(-1===c.inArray(a,g.byPassKeys)){var a=e.getMasked(),f=e.getCaret();setTimeout(function(){e.setCaret(e.calculateCaretPosition())},c.jMaskGlobals.keyStrokeCompensation);e.val(a);e.setCaret(f);return e.callbacks(d)}},getMasked:function(b,c){var h=[],k=void 0===c?e.val():c+"",q=0,C=d.length,s=0,u=k.length,p=1,l="push",m=-1,n=0,A=[],v,x;a.reverse?(l="unshift",p=-1,v=0,q=C-1,s=u-1,x=function(){return-1<
q&&-1<s}):(v=C-1,x=function(){return q<C&&s<u});for(var F;x();){var D=d.charAt(q),B=k.charAt(s),y=g.translation[D];if(y)B.match(y.pattern)?(h[l](B),y.recursive&&(-1===m?m=q:q===v&&q!==m&&(q=m-p),v===m&&(q-=p)),q+=p):B===F?(n--,F=void 0):y.optional?(q+=p,s-=p):y.fallback?(h[l](y.fallback),q+=p,s-=p):e.invalid.push({p:s,v:B,e:y.pattern}),s+=p;else{if(!b)h[l](D);B===D?(A.push(s),s+=p):(F=D,A.push(s+n),n++);q+=p}}k=d.charAt(v);C!==u+1||g.translation[k]||h.push(k);h=h.join("");e.mapMaskdigitPositions(h,
A,u);return h},mapMaskdigitPositions:function(b,d,c){b=a.reverse?b.length-c:0;e.maskDigitPosMap={};for(c=0;c<d.length;c++)e.maskDigitPosMap[d[c]+b]=1},callbacks:function(c){var g=e.val(),k=g!==h,w=[g,c,b,a],q=function(b,d,c){"function"===typeof a[b]&&d&&a[b].apply(this,c)};q("onChange",!0===k,w);q("onKeyPress",!0===k,w);q("onComplete",g.length===d.length,w);q("onInvalid",0<e.invalid.length,[g,c,b,e.invalid,a])}};b=c(b);var g=this,h=e.val(),k;d="function"===typeof d?d(e.val(),void 0,b,a):d;g.mask=
d;g.options=a;g.remove=function(){var d=e.getCaret();g.options.placeholder&&b.removeAttr("placeholder");b.data("mask-maxlength")&&b.removeAttr("maxlength");e.destroyEvents();e.val(g.getCleanVal());e.setCaret(d);return b};g.getCleanVal=function(){return e.getMasked(!0)};g.getMaskedVal=function(b){return e.getMasked(!1,b)};g.init=function(h){h=h||!1;a=a||{};g.clearIfNotMatch=c.jMaskGlobals.clearIfNotMatch;g.byPassKeys=c.jMaskGlobals.byPassKeys;g.translation=c.extend({},c.jMaskGlobals.translation,a.translation);
g=c.extend(!0,{},g,a);k=e.getRegexMask();if(h)e.events(),e.val(e.getMasked());else{a.placeholder&&b.attr("placeholder",a.placeholder);b.data("mask")&&b.attr("autocomplete","off");h=0;for(var z=!0;h<d.length;h++){var l=g.translation[d.charAt(h)];if(l&&l.recursive){z=!1;break}}z&&b.attr("maxlength",d.length).data("mask-maxlength",!0);e.destroyEvents();e.events();h=e.getCaret();e.val(e.getMasked());e.setCaret(h)}};g.init(!b.is("input"))};c.maskWatchers={};var n=function(){var b=c(this),d={},a=b.attr("data-mask");
b.attr("data-mask-reverse")&&(d.reverse=!0);b.attr("data-mask-clearifnotmatch")&&(d.clearIfNotMatch=!0);"true"===b.attr("data-mask-selectonfocus")&&(d.selectOnFocus=!0);if(m(b,a,d))return b.data("mask",new l(this,a,d))},m=function(b,d,a){a=a||{};var e=c(b).data("mask"),g=JSON.stringify;b=c(b).val()||c(b).text();try{return"function"===typeof d&&(d=d(b)),"object"!==typeof e||g(e.options)!==g(a)||e.mask!==d}catch(h){}},a=function(b){var d=document.createElement("div"),a;b="on"+b;a=b in d;a||(d.setAttribute(b,
"return;"),a="function"===typeof d[b]);return a};c.fn.mask=function(b,d){d=d||{};var a=this.selector,e=c.jMaskGlobals,g=e.watchInterval,e=d.watchInputs||e.watchInputs,h=function(){if(m(this,b,d))return c(this).data("mask",new l(this,b,d))};c(this).each(h);a&&""!==a&&e&&(clearInterval(c.maskWatchers[a]),c.maskWatchers[a]=setInterval(function(){c(document).find(a).each(h)},g));return this};c.fn.masked=function(b){return this.data("mask").getMaskedVal(b)};c.fn.unmask=function(){clearInterval(c.maskWatchers[this.selector]);
delete c.maskWatchers[this.selector];return this.each(function(){var b=c(this).data("mask");b&&b.remove().removeData("mask")})};c.fn.cleanVal=function(){return this.data("mask").getCleanVal()};c.applyDataMask=function(b){b=b||c.jMaskGlobals.maskElements;(b instanceof c?b:c(b)).filter(c.jMaskGlobals.dataMaskAttr).each(n)};a={maskElements:"input,td,span,div",dataMaskAttr:"*[data-mask]",dataMask:!0,watchInterval:300,watchInputs:!0,keyStrokeCompensation:10,useInput:!/Chrome\/[2-4][0-9]|SamsungBrowser/.test(window.navigator.userAgent)&&
a("input"),watchDataMask:!1,byPassKeys:[9,16,17,18,36,37,38,39,40,91],translation:{0:{pattern:/\d/},9:{pattern:/\d/,optional:!0},"#":{pattern:/\d/,recursive:!0},A:{pattern:/[a-zA-Z0-9]/},S:{pattern:/[a-zA-Z]/}}};c.jMaskGlobals=c.jMaskGlobals||{};a=c.jMaskGlobals=c.extend(!0,{},a,c.jMaskGlobals);a.dataMask&&c.applyDataMask();setInterval(function(){c.jMaskGlobals.watchDataMask&&c.applyDataMask()},a.watchInterval)},window.jQuery,window.Zepto);(function(c){"function"==typeof define&&define.amd?define(["jquery"],c):c(jQuery)})(function(c){c.ui=c.ui||{};c.ui.version="1.12.1";var l=0,n=Array.prototype.slice;c.cleanData=function(a){return function(b){var d,f,e;for(e=0;null!=(f=b[e]);e++)try{(d=c._data(f,"events"))&&d.remove&&c(f).triggerHandler("remove")}catch(g){}a(b)}}(c.cleanData);c.widget=function(a,b,d){var f,e,g,h={},k=a.split(".")[0];a=a.split(".")[1];var r=k+"-"+a;return d||(d=b,b=c.Widget),c.isArray(d)&&(d=c.extend.apply(null,[{}].concat(d))),
c.expr[":"][r.toLowerCase()]=function(b){return!!c.data(b,r)},c[k]=c[k]||{},f=c[k][a],e=c[k][a]=function(b,d){return this._createWidget?(arguments.length&&this._createWidget(b,d),void 0):new e(b,d)},c.extend(e,f,{version:d.version,_proto:c.extend({},d),_childConstructors:[]}),g=new b,g.options=c.widget.extend({},g.options),c.each(d,function(d,a){return c.isFunction(a)?(h[d]=function(){function c(){return b.prototype[d].apply(this,arguments)}function f(a){return b.prototype[d].apply(this,a)}return function(){var b,
d=this._super,e=this._superApply;return this._super=c,this._superApply=f,b=a.apply(this,arguments),this._super=d,this._superApply=e,b}}(),void 0):(h[d]=a,void 0)}),e.prototype=c.widget.extend(g,{widgetEventPrefix:f?g.widgetEventPrefix||a:a},h,{constructor:e,namespace:k,widgetName:a,widgetFullName:r}),f?(c.each(f._childConstructors,function(b,d){var a=d.prototype;c.widget(a.namespace+"."+a.widgetName,e,d._proto)}),delete f._childConstructors):b._childConstructors.push(e),c.widget.bridge(a,e),e};c.widget.extend=
function(a){for(var b,d,f=n.call(arguments,1),e=0,g=f.length;g>e;e++)for(b in f[e])d=f[e][b],f[e].hasOwnProperty(b)&&void 0!==d&&(a[b]=c.isPlainObject(d)?c.isPlainObject(a[b])?c.widget.extend({},a[b],d):c.widget.extend({},d):d);return a};c.widget.bridge=function(a,b){var d=b.prototype.widgetFullName||a;c.fn[a]=function(f){var e="string"==typeof f,g=n.call(arguments,1),h=this;return e?this.length||"instance"!==f?this.each(function(){var b,e=c.data(this,d);return"instance"===f?(h=e,!1):e?c.isFunction(e[f])&&
"_"!==f.charAt(0)?(b=e[f].apply(e,g),b!==e&&void 0!==b?(h=b&&b.jquery?h.pushStack(b.get()):b,!1):void 0):c.error("no such method '"+f+"' for "+a+" widget instance"):c.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+f+"'")}):h=void 0:(g.length&&(f=c.widget.extend.apply(null,[f].concat(g))),this.each(function(){var a=c.data(this,d);a?(a.option(f||{}),a._init&&a._init()):c.data(this,d,new b(f,this))})),h}};c.Widget=function(){};c.Widget._childConstructors=[];
c.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{classes:{},disabled:!1,create:null},_createWidget:function(a,b){b=c(b||this.defaultElement||this)[0];this.element=c(b);this.uuid=l++;this.eventNamespace="."+this.widgetName+this.uuid;this.bindings=c();this.hoverable=c();this.focusable=c();this.classesElementLookup={};b!==this&&(c.data(b,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===b&&this.destroy()}}),this.document=c(b.style?
b.ownerDocument:b.document||b),this.window=c(this.document[0].defaultView||this.document[0].parentWindow));this.options=c.widget.extend({},this.options,this._getCreateOptions(),a);this._create();this.options.disabled&&this._setOptionDisabled(this.options.disabled);this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:function(){return{}},_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){var a=this;this._destroy();c.each(this.classesElementLookup,
function(b,d){a._removeClass(d,b)});this.element.off(this.eventNamespace).removeData(this.widgetFullName);this.widget().off(this.eventNamespace).removeAttr("aria-disabled");this.bindings.off(this.eventNamespace)},_destroy:c.noop,widget:function(){return this.element},option:function(a,b){var d,f,e,g=a;if(0===arguments.length)return c.widget.extend({},this.options);if("string"==typeof a)if(g={},d=a.split("."),a=d.shift(),d.length){f=g[a]=c.widget.extend({},this.options[a]);for(e=0;d.length-1>e;e++)f[d[e]]=
f[d[e]]||{},f=f[d[e]];if(a=d.pop(),1===arguments.length)return void 0===f[a]?null:f[a];f[a]=b}else{if(1===arguments.length)return void 0===this.options[a]?null:this.options[a];g[a]=b}return this._setOptions(g),this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){return"classes"===a&&this._setOptionClasses(b),this.options[a]=b,"disabled"===a&&this._setOptionDisabled(b),this},_setOptionClasses:function(a){var b,d,f;for(b in a)f=this.classesElementLookup[b],
a[b]!==this.options.classes[b]&&f&&f.length&&(d=c(f.get()),this._removeClass(f,b),d.addClass(this._classes({element:d,keys:b,classes:a,add:!0})))},_setOptionDisabled:function(a){this._toggleClass(this.widget(),this.widgetFullName+"-disabled",null,!!a);a&&(this._removeClass(this.hoverable,null,"ui-state-hover"),this._removeClass(this.focusable,null,"ui-state-focus"))},enable:function(){return this._setOptions({disabled:!1})},disable:function(){return this._setOptions({disabled:!0})},_classes:function(a){function b(b,
g){var h,k;for(k=0;b.length>k;k++)h=f.classesElementLookup[b[k]]||c(),h=a.add?c(c.unique(h.get().concat(a.element.get()))):c(h.not(a.element).get()),f.classesElementLookup[b[k]]=h,d.push(b[k]),g&&a.classes[b[k]]&&d.push(a.classes[b[k]])}var d=[],f=this;return a=c.extend({element:this.element,classes:this.options.classes||{}},a),this._on(a.element,{remove:"_untrackClassesElement"}),a.keys&&b(a.keys.match(/\S+/g)||[],!0),a.extra&&b(a.extra.match(/\S+/g)||[]),d.join(" ")},_untrackClassesElement:function(a){var b=
this;c.each(b.classesElementLookup,function(d,f){-1!==c.inArray(a.target,f)&&(b.classesElementLookup[d]=c(f.not(a.target).get()))})},_removeClass:function(a,b,d){return this._toggleClass(a,b,d,!1)},_addClass:function(a,b,d){return this._toggleClass(a,b,d,!0)},_toggleClass:function(a,b,d,c){c="boolean"==typeof c?c:d;var e="string"==typeof a||null===a;a={extra:e?b:d,keys:e?a:b,element:e?this.element:a,add:c};return a.element.toggleClass(this._classes(a),c),this},_on:function(a,b,d){var f,e=this;"boolean"!=
typeof a&&(d=b,b=a,a=!1);d?(b=f=c(b),this.bindings=this.bindings.add(b)):(d=b,b=this.element,f=this.widget());c.each(d,function(d,h){function k(){return a||!0!==e.options.disabled&&!c(this).hasClass("ui-state-disabled")?("string"==typeof h?e[h]:h).apply(e,arguments):void 0}"string"!=typeof h&&(k.guid=h.guid=h.guid||k.guid||c.guid++);var r=d.match(/^([\w:-]*)\s*(.*)$/),l=r[1]+e.eventNamespace;(r=r[2])?f.on(l,r,k):b.on(l,k)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;
a.off(b).off(b);this.bindings=c(this.bindings.not(a).get());this.focusable=c(this.focusable.not(a).get());this.hoverable=c(this.hoverable.not(a).get())},_delay:function(a,b){var d=this;return setTimeout(function(){return("string"==typeof a?d[a]:a).apply(d,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(b){this._addClass(c(b.currentTarget),null,"ui-state-hover")},mouseleave:function(b){this._removeClass(c(b.currentTarget),null,"ui-state-hover")}})},
_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(b){this._addClass(c(b.currentTarget),null,"ui-state-focus")},focusout:function(b){this._removeClass(c(b.currentTarget),null,"ui-state-focus")}})},_trigger:function(a,b,d){var f,e=this.options[a];if(d=d||{},b=c.Event(b),b.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase(),b.target=this.element[0],a=b.originalEvent)for(f in a)f in b||(b[f]=a[f]);return this.element.trigger(b,d),!(c.isFunction(e)&&
!1===e.apply(this.element[0],[b].concat(d))||b.isDefaultPrevented())}};c.each({show:"fadeIn",hide:"fadeOut"},function(a,b){c.Widget.prototype["_"+a]=function(d,f,e){"string"==typeof f&&(f={effect:f});var g,h=f?!0===f||"number"==typeof f?b:f.effect||b:a;f=f||{};"number"==typeof f&&(f={duration:f});g=!c.isEmptyObject(f);f.complete=e;f.delay&&d.delay(f.delay);g&&c.effects&&c.effects.effect[h]?d[a](f):h!==a&&d[h]?d[h](f.duration,f.easing,e):d.queue(function(b){c(this)[a]();e&&e.call(d[0]);b()})}});c.widget;
(function(){function a(b,a,d){return[parseFloat(b[0])*(l.test(b[0])?a/100:1),parseFloat(b[1])*(l.test(b[1])?d/100:1)]}function b(b){var a=b[0];return 9===a.nodeType?{width:b.width(),height:b.height(),offset:{top:0,left:0}}:c.isWindow(a)?{width:b.width(),height:b.height(),offset:{top:b.scrollTop(),left:b.scrollLeft()}}:a.preventDefault?{width:0,height:0,offset:{top:a.pageY,left:a.pageX}}:{width:b.outerWidth(),height:b.outerHeight(),offset:b.offset()}}var d,f=Math.max,e=Math.abs,g=/left|center|right/,
h=/top|center|bottom/,k=/[\+\-]\d+(\.[\d]+)?%?/,r=/^\w+/,l=/%$/,m=c.fn.position;c.position={scrollbarWidth:function(){if(void 0!==d)return d;var b,a,f=c("<div style='display:block;position:absolute;width:50px;height:50px;overflow:hidden;'><div style='height:100px;width:auto;'></div></div>"),e=f.children()[0];return c("body").append(f),b=e.offsetWidth,f.css("overflow","scroll"),a=e.offsetWidth,b===a&&(a=f[0].clientWidth),f.remove(),d=b-a},getScrollInfo:function(b){var a=b.isWindow||b.isDocument?"":
b.element.css("overflow-x"),d=b.isWindow||b.isDocument?"":b.element.css("overflow-y"),a="scroll"===a||"auto"===a&&b.width<b.element[0].scrollWidth;return{width:"scroll"===d||"auto"===d&&b.height<b.element[0].scrollHeight?c.position.scrollbarWidth():0,height:a?c.position.scrollbarWidth():0}},getWithinInfo:function(b){var a=c(b||window),d=c.isWindow(a[0]),f=!!a[0]&&9===a[0].nodeType;return{element:a,isWindow:d,isDocument:f,offset:d||f?{left:0,top:0}:c(b).offset(),scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),
width:a.outerWidth(),height:a.outerHeight()}}};c.fn.position=function(d){if(!d||!d.of)return m.apply(this,arguments);d=c.extend({},d);var q,l,s,u,p,n,z=c(d.of),G=c.position.getWithinInfo(d.within),A=c.position.getScrollInfo(G),v=(d.collision||"flip").split(" "),x={};return n=b(z),z[0].preventDefault&&(d.at="left top"),l=n.width,s=n.height,u=n.offset,p=c.extend({},u),c.each(["my","at"],function(){var b,a,c=(d[this]||"").split(" ");1===c.length&&(c=g.test(c[0])?c.concat(["center"]):h.test(c[0])?["center"].concat(c):
["center","center"]);c[0]=g.test(c[0])?c[0]:"center";c[1]=h.test(c[1])?c[1]:"center";b=k.exec(c[0]);a=k.exec(c[1]);x[this]=[b?b[0]:0,a?a[0]:0];d[this]=[r.exec(c[0])[0],r.exec(c[1])[0]]}),1===v.length&&(v[1]=v[0]),"right"===d.at[0]?p.left+=l:"center"===d.at[0]&&(p.left+=l/2),"bottom"===d.at[1]?p.top+=s:"center"===d.at[1]&&(p.top+=s/2),q=a(x.at,l,s),p.left+=q[0],p.top+=q[1],this.each(function(){var b,g,h=c(this),k=h.outerWidth(),r=h.outerHeight(),m=parseInt(c.css(this,"marginLeft"),10)||0,n=parseInt(c.css(this,
"marginTop"),10)||0,I=k+m+(parseInt(c.css(this,"marginRight"),10)||0)+A.width,H=r+n+(parseInt(c.css(this,"marginBottom"),10)||0)+A.height,t=c.extend({},p),E=a(x.my,h.outerWidth(),h.outerHeight());"right"===d.my[0]?t.left-=k:"center"===d.my[0]&&(t.left-=k/2);"bottom"===d.my[1]?t.top-=r:"center"===d.my[1]&&(t.top-=r/2);t.left+=E[0];t.top+=E[1];b={marginLeft:m,marginTop:n};c.each(["left","top"],function(a,f){c.ui.position[v[a]]&&c.ui.position[v[a]][f](t,{targetWidth:l,targetHeight:s,elemWidth:k,elemHeight:r,
collisionPosition:b,collisionWidth:I,collisionHeight:H,offset:[q[0]+E[0],q[1]+E[1]],my:d.my,at:d.at,within:G,elem:h})});d.using&&(g=function(b){var a=u.left-t.left,c=a+l-k,g=u.top-t.top,q=g+s-r,p={target:{element:z,left:u.left,top:u.top,width:l,height:s},element:{element:h,left:t.left,top:t.top,width:k,height:r},horizontal:0>c?"left":0<a?"right":"center",vertical:0>q?"top":0<g?"bottom":"middle"};k>l&&l>e(a+c)&&(p.horizontal="center");r>s&&s>e(g+q)&&(p.vertical="middle");p.important=f(e(a),e(c))>f(e(g),
e(q))?"horizontal":"vertical";d.using.call(this,b,p)});h.offset(c.extend(t,{using:g}))})};c.ui.position={fit:{left:function(b,a){var d,c=a.within,e=c.isWindow?c.scrollLeft:c.offset.left,c=c.width,g=b.left-a.collisionPosition.marginLeft,h=e-g,k=g+a.collisionWidth-c-e;a.collisionWidth>c?0<h&&0>=k?(d=b.left+h+a.collisionWidth-c-e,b.left+=h-d):b.left=0<k&&0>=h?e:h>k?e+c-a.collisionWidth:e:0<h?b.left+=h:0<k?b.left-=k:b.left=f(b.left-g,b.left)},top:function(b,a){var d,c=a.within,c=c.isWindow?c.scrollTop:
c.offset.top,e=a.within.height,g=b.top-a.collisionPosition.marginTop,h=c-g,k=g+a.collisionHeight-e-c;a.collisionHeight>e?0<h&&0>=k?(d=b.top+h+a.collisionHeight-e-c,b.top+=h-d):b.top=0<k&&0>=h?c:h>k?c+e-a.collisionHeight:c:0<h?b.top+=h:0<k?b.top-=k:b.top=f(b.top-g,b.top)}},flip:{left:function(b,a){var d,c,f=a.within,g=f.offset.left+f.scrollLeft,h=f.width,f=f.isWindow?f.scrollLeft:f.offset.left,k=b.left-a.collisionPosition.marginLeft,l=k-f,k=k+a.collisionWidth-h-f,r="left"===a.my[0]?-a.elemWidth:"right"===
a.my[0]?a.elemWidth:0,m="left"===a.at[0]?a.targetWidth:"right"===a.at[0]?-a.targetWidth:0,n=-2*a.offset[0];0>l?(d=b.left+r+m+n+a.collisionWidth-h-g,(0>d||e(l)>d)&&(b.left+=r+m+n)):0<k&&(c=b.left-a.collisionPosition.marginLeft+r+m+n-f,(0<c||k>e(c))&&(b.left+=r+m+n))},top:function(b,a){var d,c,f=a.within,g=f.offset.top+f.scrollTop,h=f.height,f=f.isWindow?f.scrollTop:f.offset.top,k=b.top-a.collisionPosition.marginTop,r=k-f,k=k+a.collisionHeight-h-f,l="top"===a.my[1]?-a.elemHeight:"bottom"===a.my[1]?
a.elemHeight:0,m="top"===a.at[1]?a.targetHeight:"bottom"===a.at[1]?-a.targetHeight:0,n=-2*a.offset[1];0>r?(c=b.top+l+m+n+a.collisionHeight-h-g,(0>c||e(r)>c)&&(b.top+=l+m+n)):0<k&&(d=b.top-a.collisionPosition.marginTop+l+m+n-f,(0<d||k>e(d))&&(b.top+=l+m+n))}},flipfit:{left:function(){c.ui.position.flip.left.apply(this,arguments);c.ui.position.fit.left.apply(this,arguments)},top:function(){c.ui.position.flip.top.apply(this,arguments);c.ui.position.fit.top.apply(this,arguments)}}}})();c.ui.position;
"1.7"===c.fn.jquery.substring(0,3)&&(c.each(["Width","Height"],function(a,b){function d(b,a,d,e){return c.each(f,function(){a-=parseFloat(c.css(b,"padding"+this))||0;d&&(a-=parseFloat(c.css(b,"border"+this+"Width"))||0);e&&(a-=parseFloat(c.css(b,"margin"+this))||0)}),a}var f="Width"===b?["Left","Right"]:["Top","Bottom"],e=b.toLowerCase(),g={innerWidth:c.fn.innerWidth,innerHeight:c.fn.innerHeight,outerWidth:c.fn.outerWidth,outerHeight:c.fn.outerHeight};c.fn["inner"+b]=function(a){return void 0===a?
g["inner"+b].call(this):this.each(function(){c(this).css(e,d(this,a)+"px")})};c.fn["outer"+b]=function(a,f){return"number"!=typeof a?g["outer"+b].call(this,a):this.each(function(){c(this).css(e,d(this,a,!0,f)+"px")})}}),c.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});c.ui.keyCode={BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38};c.fn.extend({uniqueId:function(){var a=
0;return function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++a)})}}(),removeUniqueId:function(){return this.each(function(){/^ui-id-\d+$/.test(this.id)&&c(this).removeAttr("id")})}});c.widget("ui.accordion",{version:"1.12.1",options:{active:0,animate:{},classes:{"ui-accordion-header":"ui-corner-top","ui-accordion-header-collapsed":"ui-corner-all","ui-accordion-content":"ui-corner-bottom"},collapsible:!1,event:"click",header:"> li > :first-child, > :not(li):even",heightStyle:"auto",
icons:{activeHeader:"ui-icon-triangle-1-s",header:"ui-icon-triangle-1-e"},activate:null,beforeActivate:null},hideProps:{borderTopWidth:"hide",borderBottomWidth:"hide",paddingTop:"hide",paddingBottom:"hide",height:"hide"},showProps:{borderTopWidth:"show",borderBottomWidth:"show",paddingTop:"show",paddingBottom:"show",height:"show"},_create:function(){var a=this.options;this.prevShow=this.prevHide=c();this._addClass("ui-accordion","ui-widget ui-helper-reset");this.element.attr("role","tablist");a.collapsible||
!1!==a.active&&null!=a.active||(a.active=0);this._processPanels();0>a.active&&(a.active+=this.headers.length);this._refresh()},_getCreateEventData:function(){return{header:this.active,panel:this.active.length?this.active.next():c()}},_createIcons:function(){var a,b,d=this.options.icons;d&&(a=c("<span>"),this._addClass(a,"ui-accordion-header-icon","ui-icon "+d.header),a.prependTo(this.headers),b=this.active.children(".ui-accordion-header-icon"),this._removeClass(b,d.header)._addClass(b,null,d.activeHeader)._addClass(this.headers,
"ui-accordion-icons"))},_destroyIcons:function(){this._removeClass(this.headers,"ui-accordion-icons");this.headers.children(".ui-accordion-header-icon").remove()},_destroy:function(){var a;this.element.removeAttr("role");this.headers.removeAttr("role aria-expanded aria-selected aria-controls tabIndex").removeUniqueId();this._destroyIcons();a=this.headers.next().css("display","").removeAttr("role aria-hidden aria-labelledby").removeUniqueId();"content"!==this.options.heightStyle&&a.css("height","")},
_setOption:function(a,b){return"active"===a?(this._activate(b),void 0):("event"===a&&(this.options.event&&this._off(this.headers,this.options.event),this._setupEvents(b)),this._super(a,b),"collapsible"!==a||b||!1!==this.options.active||this._activate(0),"icons"===a&&(this._destroyIcons(),b&&this._createIcons()),void 0)},_setOptionDisabled:function(a){this._super(a);this.element.attr("aria-disabled",a);this._toggleClass(null,"ui-state-disabled",!!a);this._toggleClass(this.headers.add(this.headers.next()),
null,"ui-state-disabled",!!a)},_keydown:function(a){if(!a.altKey&&!a.ctrlKey){var b=c.ui.keyCode,d=this.headers.length,f=this.headers.index(a.target),e=!1;switch(a.keyCode){case b.RIGHT:case b.DOWN:e=this.headers[(f+1)%d];break;case b.LEFT:case b.UP:e=this.headers[(f-1+d)%d];break;case b.SPACE:case b.ENTER:this._eventHandler(a);break;case b.HOME:e=this.headers[0];break;case b.END:e=this.headers[d-1]}e&&(c(a.target).attr("tabIndex",-1),c(e).attr("tabIndex",0),c(e).trigger("focus"),a.preventDefault())}},
_panelKeyDown:function(a){a.keyCode===c.ui.keyCode.UP&&a.ctrlKey&&c(a.currentTarget).prev().trigger("focus")},refresh:function(){var a=this.options;this._processPanels();!1===a.active&&!0===a.collapsible||!this.headers.length?(a.active=!1,this.active=c()):!1===a.active?this._activate(0):this.active.length&&!c.contains(this.element[0],this.active[0])?this.headers.length===this.headers.find(".ui-state-disabled").length?(a.active=!1,this.active=c()):this._activate(Math.max(0,a.active-1)):a.active=this.headers.index(this.active);
this._destroyIcons();this._refresh()},_processPanels:function(){var a=this.headers,b=this.panels;this.headers=this.element.find(this.options.header);this._addClass(this.headers,"ui-accordion-header ui-accordion-header-collapsed","ui-state-default");this.panels=this.headers.next().filter(":not(.ui-accordion-content-active)").hide();this._addClass(this.panels,"ui-accordion-content","ui-helper-reset ui-widget-content");b&&(this._off(a.not(this.headers)),this._off(b.not(this.panels)))},_refresh:function(){var a,
b=this.options,d=b.heightStyle,f=this.element.parent();this.active=this._findActive(b.active);this._addClass(this.active,"ui-accordion-header-active","ui-state-active")._removeClass(this.active,"ui-accordion-header-collapsed");this._addClass(this.active.next(),"ui-accordion-content-active");this.active.next().show();this.headers.attr("role","tab").each(function(){var b=c(this),a=b.uniqueId().attr("id"),d=b.next(),f=d.uniqueId().attr("id");b.attr("aria-controls",f);d.attr("aria-labelledby",a)}).next().attr("role",
"tabpanel");this.headers.not(this.active).attr({"aria-selected":"false","aria-expanded":"false",tabIndex:-1}).next().attr({"aria-hidden":"true"}).hide();this.active.length?this.active.attr({"aria-selected":"true","aria-expanded":"true",tabIndex:0}).next().attr({"aria-hidden":"false"}):this.headers.eq(0).attr("tabIndex",0);this._createIcons();this._setupEvents(b.event);"fill"===d?(a=f.height(),this.element.siblings(":visible").each(function(){var b=c(this),d=b.css("position");"absolute"!==d&&"fixed"!==
d&&(a-=b.outerHeight(!0))}),this.headers.each(function(){a-=c(this).outerHeight(!0)}),this.headers.next().each(function(){c(this).height(Math.max(0,a-c(this).innerHeight()+c(this).height()))}).css("overflow","auto")):"auto"===d&&(a=0,this.headers.next().each(function(){var b=c(this).is(":visible");b||c(this).show();a=Math.max(a,c(this).css("height","").height());b||c(this).hide()}).height(a))},_activate:function(a){a=this._findActive(a)[0];a!==this.active[0]&&(a=a||this.active[0],this._eventHandler({target:a,
currentTarget:a,preventDefault:c.noop}))},_findActive:function(a){return"number"==typeof a?this.headers.eq(a):c()},_setupEvents:function(a){var b={keydown:"_keydown"};a&&c.each(a.split(" "),function(a,c){b[c]="_eventHandler"});this._off(this.headers.add(this.headers.next()));this._on(this.headers,b);this._on(this.headers.next(),{keydown:"_panelKeyDown"});this._hoverable(this.headers);this._focusable(this.headers)},_eventHandler:function(a){var b,d,f=this.options,e=this.active,g=c(a.currentTarget),
h=g[0]===e[0],k=h&&f.collapsible,l=k?c():g.next(),m=e.next(),l={oldHeader:e,oldPanel:m,newHeader:k?c():g,newPanel:l};a.preventDefault();h&&!f.collapsible||!1===this._trigger("beforeActivate",a,l)||(f.active=k?!1:this.headers.index(g),this.active=h?c():g,this._toggle(l),this._removeClass(e,"ui-accordion-header-active","ui-state-active"),f.icons&&(b=e.children(".ui-accordion-header-icon"),this._removeClass(b,null,f.icons.activeHeader)._addClass(b,null,f.icons.header)),h||(this._removeClass(g,"ui-accordion-header-collapsed")._addClass(g,
"ui-accordion-header-active","ui-state-active"),f.icons&&(d=g.children(".ui-accordion-header-icon"),this._removeClass(d,null,f.icons.header)._addClass(d,null,f.icons.activeHeader)),this._addClass(g.next(),"ui-accordion-content-active")))},_toggle:function(a){var b=a.newPanel,d=this.prevShow.length?this.prevShow:a.oldPanel;this.prevShow.add(this.prevHide).stop(!0,!0);this.prevShow=b;this.prevHide=d;this.options.animate?this._animate(b,d,a):(d.hide(),b.show(),this._toggleComplete(a));d.attr({"aria-hidden":"true"});
d.prev().attr({"aria-selected":"false","aria-expanded":"false"});b.length&&d.length?d.prev().attr({tabIndex:-1,"aria-expanded":"false"}):b.length&&this.headers.filter(function(){return 0===parseInt(c(this).attr("tabIndex"),10)}).attr("tabIndex",-1);b.attr("aria-hidden","false").prev().attr({"aria-selected":"true","aria-expanded":"true",tabIndex:0})},_animate:function(a,b,d){var c,e,g,h=this,k=0,l=a.css("box-sizing"),m=a.length&&(!b.length||a.index()<b.index()),n=this.options.animate||{},m=m&&n.down||
n,w=function(){h._toggleComplete(d)};return"number"==typeof m&&(g=m),"string"==typeof m&&(e=m),e=e||m.easing||n.easing,g=g||m.duration||n.duration,b.length?a.length?(c=a.show().outerHeight(),b.animate(this.hideProps,{duration:g,easing:e,step:function(b,a){a.now=Math.round(b)}}),a.hide().animate(this.showProps,{duration:g,easing:e,complete:w,step:function(a,d){d.now=Math.round(a);"height"!==d.prop?"content-box"===l&&(k+=d.now):"content"!==h.options.heightStyle&&(d.now=Math.round(c-b.outerHeight()-
k),k=0)}}),void 0):b.animate(this.hideProps,g,e,w):a.animate(this.showProps,g,e,w)},_toggleComplete:function(a){var b=a.oldPanel,d=b.prev();this._removeClass(b,"ui-accordion-content-active");this._removeClass(d,"ui-accordion-header-active")._addClass(d,"ui-accordion-header-collapsed");b.length&&(b.parent()[0].className=b.parent()[0].className);this._trigger("activate",null,a)}});c.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());var m=!1;c(document).on("mouseup",function(){m=!1});c.widget("ui.mouse",
{version:"1.12.1",options:{cancel:"input, textarea, button, select, option",distance:1,delay:0},_mouseInit:function(){var a=this;this.element.on("mousedown."+this.widgetName,function(b){return a._mouseDown(b)}).on("click."+this.widgetName,function(b){return!0===c.data(b.target,a.widgetName+".preventClickEvent")?(c.removeData(b.target,a.widgetName+".preventClickEvent"),b.stopImmediatePropagation(),!1):void 0});this.started=!1},_mouseDestroy:function(){this.element.off("."+this.widgetName);this._mouseMoveDelegate&&
this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(a){if(!m){this._mouseMoved=!1;this._mouseStarted&&this._mouseUp(a);this._mouseDownEvent=a;var b=this,d=1===a.which,f="string"==typeof this.options.cancel&&a.target.nodeName?c(a.target).closest(this.options.cancel).length:!1;return d&&!f&&this._mouseCapture(a)?(this.mouseDelayMet=!this.options.delay,this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){b.mouseDelayMet=
!0},this.options.delay)),this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(a),!this._mouseStarted)?(a.preventDefault(),!0):(!0===c.data(a.target,this.widgetName+".preventClickEvent")&&c.removeData(a.target,this.widgetName+".preventClickEvent"),this._mouseMoveDelegate=function(a){return b._mouseMove(a)},this._mouseUpDelegate=function(a){return b._mouseUp(a)},this.document.on("mousemove."+this.widgetName,this._mouseMoveDelegate).on("mouseup."+this.widgetName,
this._mouseUpDelegate),a.preventDefault(),m=!0,!0)):!0}},_mouseMove:function(a){if(this._mouseMoved){if(c.ui.ie&&(!document.documentMode||9>document.documentMode)&&!a.button)return this._mouseUp(a);if(!a.which)if(a.originalEvent.altKey||a.originalEvent.ctrlKey||a.originalEvent.metaKey||a.originalEvent.shiftKey)this.ignoreMissingWhich=!0;else if(!this.ignoreMissingWhich)return this._mouseUp(a)}return(a.which||a.button)&&(this._mouseMoved=!0),this._mouseStarted?(this._mouseDrag(a),a.preventDefault()):
(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,a),this._mouseStarted?this._mouseDrag(a):this._mouseUp(a)),!this._mouseStarted)},_mouseUp:function(a){this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,a.target===this._mouseDownEvent.target&&c.data(a.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(a));
this._mouseDelayTimer&&(clearTimeout(this._mouseDelayTimer),delete this._mouseDelayTimer);m=this.ignoreMissingWhich=!1;a.preventDefault()},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}});c.widget("ui.slider",c.ui.mouse,{version:"1.12.1",
widgetEventPrefix:"slide",options:{animate:!1,classes:{"ui-slider":"ui-corner-all","ui-slider-handle":"ui-corner-all","ui-slider-range":"ui-corner-all ui-widget-header"},distance:0,max:100,min:0,orientation:"horizontal",range:!1,step:1,value:0,values:null,change:null,slide:null,start:null,stop:null},numPages:5,_create:function(){this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this._calculateNewMax();this._addClass("ui-slider ui-slider-"+
this.orientation,"ui-widget ui-widget-content");this._refresh();this._animateOff=!1},_refresh:function(){this._createRange();this._createHandles();this._setupEvents();this._refreshValue()},_createHandles:function(){var a,b;a=this.options;var d=this.element.find(".ui-slider-handle"),f=[];b=a.values&&a.values.length||1;d.length>b&&(d.slice(b).remove(),d=d.slice(0,b));for(a=d.length;b>a;a++)f.push("<span tabindex='0'></span>");this.handles=d.add(c(f.join("")).appendTo(this.element));this._addClass(this.handles,
"ui-slider-handle","ui-state-default");this.handle=this.handles.eq(0);this.handles.each(function(b){c(this).data("ui-slider-handle-index",b).attr("tabIndex",0)})},_createRange:function(){var a=this.options;a.range?(!0===a.range&&(a.values?a.values.length&&2!==a.values.length?a.values=[a.values[0],a.values[0]]:c.isArray(a.values)&&(a.values=a.values.slice(0)):a.values=[this._valueMin(),this._valueMin()]),this.range&&this.range.length?(this._removeClass(this.range,"ui-slider-range-min ui-slider-range-max"),
this.range.css({left:"",bottom:""})):(this.range=c("<div>").appendTo(this.element),this._addClass(this.range,"ui-slider-range")),("min"===a.range||"max"===a.range)&&this._addClass(this.range,"ui-slider-range-"+a.range)):(this.range&&this.range.remove(),this.range=null)},_setupEvents:function(){this._off(this.handles);this._on(this.handles,this._handleEvents);this._hoverable(this.handles);this._focusable(this.handles)},_destroy:function(){this.handles.remove();this.range&&this.range.remove();this._mouseDestroy()},
_mouseCapture:function(a){var b,d,f,e,g,h,k,l,m=this,n=this.options;return n.disabled?!1:(this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()},this.elementOffset=this.element.offset(),b={x:a.pageX,y:a.pageY},d=this._normValueFromMouse(b),f=this._valueMax()-this._valueMin()+1,this.handles.each(function(b){var a=Math.abs(d-m.values(b));(f>a||f===a&&(b===m._lastChangedValue||m.values(b)===n.min))&&(f=a,e=c(this),g=b)}),h=this._start(a,g),!1===h?!1:(this._mouseSliding=
!0,this._handleIndex=g,this._addClass(e,null,"ui-state-active"),e.trigger("focus"),k=e.offset(),l=!c(a.target).parents().addBack().is(".ui-slider-handle"),this._clickOffset=l?{left:0,top:0}:{left:a.pageX-k.left-e.width()/2,top:a.pageY-k.top-e.height()/2-(parseInt(e.css("borderTopWidth"),10)||0)-(parseInt(e.css("borderBottomWidth"),10)||0)+(parseInt(e.css("marginTop"),10)||0)},this.handles.hasClass("ui-state-hover")||this._slide(a,g,d),this._animateOff=!0,!0))},_mouseStart:function(){return!0},_mouseDrag:function(a){var b=
this._normValueFromMouse({x:a.pageX,y:a.pageY});return this._slide(a,this._handleIndex,b),!1},_mouseStop:function(a){return this._removeClass(this.handles,null,"ui-state-active"),this._mouseSliding=!1,this._stop(a,this._handleIndex),this._change(a,this._handleIndex),this._handleIndex=null,this._clickOffset=null,this._animateOff=!1,!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(a){var b,d,c,e,g;return"horizontal"===
this.orientation?(b=this.elementSize.width,d=a.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(b=this.elementSize.height,d=a.y-this.elementOffset.top-(this._clickOffset?this._clickOffset.top:0)),c=d/b,1<c&&(c=1),0>c&&(c=0),"vertical"===this.orientation&&(c=1-c),e=this._valueMax()-this._valueMin(),g=this._valueMin()+c*e,this._trimAlignValue(g)},_uiHash:function(a,b,d){var c={handle:this.handles[a],handleIndex:a,value:void 0!==b?b:this.value()};return this._hasMultipleValues()&&
(c.value=void 0!==b?b:this.values(a),c.values=d||this.values()),c},_hasMultipleValues:function(){return this.options.values&&this.options.values.length},_start:function(a,b){return this._trigger("start",a,this._uiHash(b))},_slide:function(a,b,d){var c,e,g=this.value(),h=this.values();this._hasMultipleValues()&&(e=this.values(b?0:1),g=this.values(b),2===this.options.values.length&&!0===this.options.range&&(d=0===b?Math.min(e,d):Math.max(e,d)),h[b]=d);d!==g&&(c=this._trigger("slide",a,this._uiHash(b,
d,h)),!1!==c&&(this._hasMultipleValues()?this.values(b,d):this.value(d)))},_stop:function(a,b){this._trigger("stop",a,this._uiHash(b))},_change:function(a,b){this._keySliding||this._mouseSliding||(this._lastChangedValue=b,this._trigger("change",a,this._uiHash(b)))},value:function(a){return arguments.length?(this.options.value=this._trimAlignValue(a),this._refreshValue(),this._change(null,0),void 0):this._value()},values:function(a,b){var d,f,e;if(1<arguments.length)return this.options.values[a]=this._trimAlignValue(b),
this._refreshValue(),this._change(null,a),void 0;if(!arguments.length)return this._values();if(!c.isArray(arguments[0]))return this._hasMultipleValues()?this._values(a):this.value();d=this.options.values;f=arguments[0];for(e=0;d.length>e;e+=1)d[e]=this._trimAlignValue(f[e]),this._change(null,e);this._refreshValue()},_setOption:function(a,b){var d;d=0;switch("range"===a&&!0===this.options.range&&("min"===b?(this.options.value=this._values(0),this.options.values=null):"max"===b&&(this.options.value=
this._values(this.options.values.length-1),this.options.values=null)),c.isArray(this.options.values)&&(d=this.options.values.length),this._super(a,b),a){case "orientation":this._detectOrientation();this._removeClass("ui-slider-horizontal ui-slider-vertical")._addClass("ui-slider-"+this.orientation);this._refreshValue();this.options.range&&this._refreshRange(b);this.handles.css("horizontal"===b?"bottom":"left","");break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=
!1;break;case "values":this._animateOff=!0;this._refreshValue();for(d-=1;0<=d;d--)this._change(null,d);this._animateOff=!1;break;case "step":case "min":case "max":this._animateOff=!0;this._calculateNewMax();this._refreshValue();this._animateOff=!1;break;case "range":this._animateOff=!0,this._refresh(),this._animateOff=!1}},_setOptionDisabled:function(a){this._super(a);this._toggleClass(null,"ui-state-disabled",!!a)},_value:function(){return this._trimAlignValue(this.options.value)},_values:function(a){var b,
d;if(arguments.length)return b=this.options.values[a],this._trimAlignValue(b);if(this._hasMultipleValues()){b=this.options.values.slice();for(d=0;b.length>d;d+=1)b[d]=this._trimAlignValue(b[d]);return b}return[]},_trimAlignValue:function(a){if(this._valueMin()>=a)return this._valueMin();if(a>=this._valueMax())return this._valueMax();var b=0<this.options.step?this.options.step:1,d=(a-this._valueMin())%b;a-=d;return 2*Math.abs(d)>=b&&(a+=0<d?b:-b),parseFloat(a.toFixed(5))},_calculateNewMax:function(){var a=
this.options.max,b=this._valueMin(),d=this.options.step,a=Math.round((a-b)/d)*d+b;a>this.options.max&&(a-=d);this.max=parseFloat(a.toFixed(this._precision()))},_precision:function(){var a=this._precisionOf(this.options.step);return null!==this.options.min&&(a=Math.max(a,this._precisionOf(this.options.min))),a},_precisionOf:function(a){a=""+a;var b=a.indexOf(".");return-1===b?0:a.length-b-1},_valueMin:function(){return this.options.min},_valueMax:function(){return this.max},_refreshRange:function(a){"vertical"===
a&&this.range.css({width:"",left:""});"horizontal"===a&&this.range.css({height:"",bottom:""})},_refreshValue:function(){var a,b,d,f,e,g=this.options.range,h=this.options,k=this,l=this._animateOff?!1:h.animate,m={};this._hasMultipleValues()?this.handles.each(function(d){b=100*((k.values(d)-k._valueMin())/(k._valueMax()-k._valueMin()));m["horizontal"===k.orientation?"left":"bottom"]=b+"%";c(this).stop(1,1)[l?"animate":"css"](m,h.animate);!0===k.options.range&&("horizontal"===k.orientation?(0===d&&k.range.stop(1,
1)[l?"animate":"css"]({left:b+"%"},h.animate),1===d&&k.range[l?"animate":"css"]({width:b-a+"%"},{queue:!1,duration:h.animate})):(0===d&&k.range.stop(1,1)[l?"animate":"css"]({bottom:b+"%"},h.animate),1===d&&k.range[l?"animate":"css"]({height:b-a+"%"},{queue:!1,duration:h.animate})));a=b}):(d=this.value(),f=this._valueMin(),e=this._valueMax(),b=e!==f?(d-f)/(e-f)*100:0,m["horizontal"===this.orientation?"left":"bottom"]=b+"%",this.handle.stop(1,1)[l?"animate":"css"](m,h.animate),"min"===g&&"horizontal"===
this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({width:b+"%"},h.animate),"max"===g&&"horizontal"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({width:100-b+"%"},h.animate),"min"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({height:b+"%"},h.animate),"max"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({height:100-b+"%"},h.animate))},_handleEvents:{keydown:function(a){var b,d,f,e=c(a.target).data("ui-slider-handle-index");
switch(a.keyCode){case c.ui.keyCode.HOME:case c.ui.keyCode.END:case c.ui.keyCode.PAGE_UP:case c.ui.keyCode.PAGE_DOWN:case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(a.preventDefault(),!this._keySliding&&(this._keySliding=!0,this._addClass(c(a.target),null,"ui-state-active"),b=this._start(a,e),!1===b))return}switch(f=this.options.step,b=d=this._hasMultipleValues()?this.values(e):this.value(),a.keyCode){case c.ui.keyCode.HOME:d=this._valueMin();break;case c.ui.keyCode.END:d=
this._valueMax();break;case c.ui.keyCode.PAGE_UP:d=this._trimAlignValue(b+(this._valueMax()-this._valueMin())/this.numPages);break;case c.ui.keyCode.PAGE_DOWN:d=this._trimAlignValue(b-(this._valueMax()-this._valueMin())/this.numPages);break;case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:if(b===this._valueMax())return;d=this._trimAlignValue(b+f);break;case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(b===this._valueMin())return;d=this._trimAlignValue(b-f)}this._slide(a,e,d)},keyup:function(a){var b=c(a.target).data("ui-slider-handle-index");
this._keySliding&&(this._keySliding=!1,this._stop(a,b),this._change(a,b),this._removeClass(c(a.target),null,"ui-state-active"))}}});c.widget("ui.tooltip",{version:"1.12.1",options:{classes:{"ui-tooltip":"ui-corner-all ui-widget-shadow"},content:function(){var a=c(this).attr("title")||"";return c("<a>").text(a).html()},hide:!0,items:"[title]:not([disabled])",position:{my:"left top+15",at:"left bottom",collision:"flipfit flip"},show:!0,track:!1,close:null,open:null},_addDescribedBy:function(a,b){var d=
(a.attr("aria-describedby")||"").split(/\s+/);d.push(b);a.data("ui-tooltip-id",b).attr("aria-describedby",c.trim(d.join(" ")))},_removeDescribedBy:function(a){var b=a.data("ui-tooltip-id"),d=(a.attr("aria-describedby")||"").split(/\s+/),b=c.inArray(b,d);-1!==b&&d.splice(b,1);a.removeData("ui-tooltip-id");(d=c.trim(d.join(" ")))?a.attr("aria-describedby",d):a.removeAttr("aria-describedby")},_create:function(){this._on({mouseover:"open",focusin:"open"});this.tooltips={};this.parents={};this.liveRegion=
c("<div>").attr({role:"log","aria-live":"assertive","aria-relevant":"additions"}).appendTo(this.document[0].body);this._addClass(this.liveRegion,null,"ui-helper-hidden-accessible");this.disabledTitles=c([])},_setOption:function(a,b){var d=this;this._super(a,b);"content"===a&&c.each(this.tooltips,function(b,a){d._updateContent(a.element)})},_setOptionDisabled:function(a){this[a?"_disable":"_enable"]()},_disable:function(){var a=this;c.each(this.tooltips,function(b,d){var f=c.Event("blur");f.target=
f.currentTarget=d.element[0];a.close(f,!0)});this.disabledTitles=this.disabledTitles.add(this.element.find(this.options.items).addBack().filter(function(){var b=c(this);return b.is("[title]")?b.data("ui-tooltip-title",b.attr("title")).removeAttr("title"):void 0}))},_enable:function(){this.disabledTitles.each(function(){var a=c(this);a.data("ui-tooltip-title")&&a.attr("title",a.data("ui-tooltip-title"))});this.disabledTitles=c([])},open:function(a){var b=this,d=c(a?a.target:this.element).closest(this.options.items);
d.length&&!d.data("ui-tooltip-id")&&(d.attr("title")&&d.data("ui-tooltip-title",d.attr("title")),d.data("ui-tooltip-open",!0),a&&"mouseover"===a.type&&d.parents().each(function(){var a,d=c(this);d.data("ui-tooltip-open")&&(a=c.Event("blur"),a.target=a.currentTarget=this,b.close(a,!0));d.attr("title")&&(d.uniqueId(),b.parents[this.id]={element:this,title:d.attr("title")},d.attr("title",""))}),this._registerCloseHandlers(a,d),this._updateContent(d,a))},_updateContent:function(a,b){var d,c=this.options.content,
e=this,g=b?b.type:null;return"string"==typeof c||c.nodeType||c.jquery?this._open(b,a,c):(d=c.call(a[0],function(d){e._delay(function(){a.data("ui-tooltip-open")&&(b&&(b.type=g),this._open(b,a,d))})}),d&&this._open(b,a,d),void 0)},_open:function(a,b,d){function f(b){k.of=b;g.is(":hidden")||g.position(k)}var e,g,h,k=c.extend({},this.options.position);if(d){if(e=this._find(b))return e.tooltip.find(".ui-tooltip-content").html(d),void 0;b.is("[title]")&&(a&&"mouseover"===a.type?b.attr("title",""):b.removeAttr("title"));
e=this._tooltip(b);g=e.tooltip;this._addDescribedBy(b,g.attr("id"));g.find(".ui-tooltip-content").html(d);this.liveRegion.children().hide();d=c("<div>").html(g.find(".ui-tooltip-content").html());d.removeAttr("name").find("[name]").removeAttr("name");d.removeAttr("id").find("[id]").removeAttr("id");d.appendTo(this.liveRegion);this.options.track&&a&&/^mouse/.test(a.type)?(this._on(this.document,{mousemove:f}),f(a)):g.position(c.extend({of:b},this.options.position));g.hide();this._show(g,this.options.show);
this.options.track&&this.options.show&&this.options.show.delay&&(h=this.delayedShow=setInterval(function(){g.is(":visible")&&(f(k.of),clearInterval(h))},c.fx.interval));this._trigger("open",a,{tooltip:g})}},_registerCloseHandlers:function(a,b){var d={keyup:function(a){a.keyCode===c.ui.keyCode.ESCAPE&&(a=c.Event(a),a.currentTarget=b[0],this.close(a,!0))}};b[0]!==this.element[0]&&(d.remove=function(){this._removeTooltip(this._find(b).tooltip)});a&&"mouseover"!==a.type||(d.mouseleave="close");a&&"focusin"!==
a.type||(d.focusout="close");this._on(!0,b,d)},close:function(a){var b,d=this,f=c(a?a.currentTarget:this.element),e=this._find(f);return e?(b=e.tooltip,e.closing||(clearInterval(this.delayedShow),f.data("ui-tooltip-title")&&!f.attr("title")&&f.attr("title",f.data("ui-tooltip-title")),this._removeDescribedBy(f),e.hiding=!0,b.stop(!0),this._hide(b,this.options.hide,function(){d._removeTooltip(c(this))}),f.removeData("ui-tooltip-open"),this._off(f,"mouseleave focusout keyup"),f[0]!==this.element[0]&&
this._off(f,"remove"),this._off(this.document,"mousemove"),a&&"mouseleave"===a.type&&c.each(this.parents,function(b,a){c(a.element).attr("title",a.title);delete d.parents[b]}),e.closing=!0,this._trigger("close",a,{tooltip:b}),e.hiding||(e.closing=!1)),void 0):(f.removeData("ui-tooltip-open"),void 0)},_tooltip:function(a){var b=c("<div>").attr("role","tooltip"),d=c("<div>").appendTo(b),f=b.uniqueId().attr("id");return this._addClass(d,"ui-tooltip-content"),this._addClass(b,"ui-tooltip","ui-widget ui-widget-content"),
b.appendTo(this._appendTo(a)),this.tooltips[f]={element:a,tooltip:b}},_find:function(a){return(a=a.data("ui-tooltip-id"))?this.tooltips[a]:null},_removeTooltip:function(a){a.remove();delete this.tooltips[a.attr("id")]},_appendTo:function(a){a=a.closest(".ui-front, dialog");return a.length||(a=this.document[0].body),a},_destroy:function(){var a=this;c.each(this.tooltips,function(b,d){var f=c.Event("blur"),e=d.element;f.target=f.currentTarget=e[0];a.close(f,!0);c("#"+b).remove();e.data("ui-tooltip-title")&&
(e.attr("title")||e.attr("title",e.data("ui-tooltip-title")),e.removeData("ui-tooltip-title"))});this.liveRegion.remove()}});!1!==c.uiBackCompat&&c.widget("ui.tooltip",c.ui.tooltip,{options:{tooltipClass:null},_tooltip:function(){var a=this._superApply(arguments);return this.options.tooltipClass&&a.tooltip.addClass(this.options.tooltipClass),a}});c.ui.tooltip});/*
 The MIT License (MIT)
 @todo Lazy Load Icon
 @todo prevent animationend bubling
 @todo itemsScaleUp
 @todo Test Zepto
 @todo stagePadding calculate wrong active classes
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
 The MIT License (MIT)
*/
(function(c,l,n,m){function a(b,d){this.settings=null;this.options=c.extend({},a.Defaults,d);this.$element=c(b);this._handlers={};this._plugins={};this._supress={};this._speed=this._current=null;this._coordinates=[];this._width=this._breakpoint=null;this._items=[];this._clones=[];this._mergers=[];this._widths=[];this._invalidated={};this._pipe=[];this._drag={time:null,target:null,pointer:null,stage:{start:null,current:null},direction:null};this._states={current:{},tags:{initializing:["busy"],animating:["busy"],
dragging:["interacting"]}};c.each(["onResize","onThrottledResize"],c.proxy(function(b,a){this._handlers[a]=c.proxy(this[a],this)},this));c.each(a.Plugins,c.proxy(function(b,a){this._plugins[b.charAt(0).toLowerCase()+b.slice(1)]=new a(this)},this));c.each(a.Workers,c.proxy(function(b,a){this._pipe.push({filter:a.filter,run:c.proxy(a.run,this)})},this));this.setup();this.initialize()}a.Defaults={items:3,loop:!1,center:!1,rewind:!1,checkVisibility:!0,mouseDrag:!0,touchDrag:!0,pullDrag:!0,freeDrag:!1,
margin:0,stagePadding:0,merge:!1,mergeFit:!0,autoWidth:!1,startPosition:0,rtl:!1,smartSpeed:250,fluidSpeed:!1,dragEndSpeed:!1,responsive:{},responsiveRefreshRate:200,responsiveBaseElement:l,fallbackEasing:"swing",slideTransition:"",info:!1,nestedItemSelector:!1,itemElement:"div",stageElement:"div",refreshClass:"owl-refresh",loadedClass:"owl-loaded",loadingClass:"owl-loading",rtlClass:"owl-rtl",responsiveClass:"owl-responsive",dragClass:"owl-drag",itemClass:"owl-item",stageClass:"owl-stage",stageOuterClass:"owl-stage-outer",
grabClass:"owl-grab"};a.Width={Default:"default",Inner:"inner",Outer:"outer"};a.Type={Event:"event",State:"state"};a.Plugins={};a.Workers=[{filter:["width","settings"],run:function(){this._width=this.$element.width()}},{filter:["width","items","settings"],run:function(b){b.current=this._items&&this._items[this.relative(this._current)]}},{filter:["items","settings"],run:function(){this.$stage.children(".cloned").remove()}},{filter:["width","items","settings"],run:function(b){var a=this.settings.margin||
"",c=this.settings.rtl,a={width:"auto","margin-left":c?a:"","margin-right":c?"":a};this.settings.autoWidth&&this.$stage.children().css(a);b.css=a}},{filter:["width","items","settings"],run:function(b){var a=(this.width()/this.settings.items).toFixed(3)-this.settings.margin,c=null,e=this._items.length,g=!this.settings.autoWidth,h=[];for(b.items={merge:!1,width:a};e--;)c=this._mergers[e],c=this.settings.mergeFit&&Math.min(c,this.settings.items)||c,b.items.merge=1<c||b.items.merge,h[e]=g?a*c:this._items[e].width();
this._widths=h}},{filter:["items","settings"],run:function(){for(var b=[],a=this._items,f=this.settings,e=Math.max(2*f.items,4),g=2*Math.ceil(a.length/2),f=f.loop&&a.length?f.rewind?e:Math.max(e,g):0,g=e="",f=f/2;0<f;)b.push(this.normalize(b.length/2,!0)),e+=a[b[b.length-1]][0].outerHTML,b.push(this.normalize(a.length-1-(b.length-1)/2,!0)),g=a[b[b.length-1]][0].outerHTML+g,f-=1;this._clones=b;c(e).addClass("cloned").appendTo(this.$stage);c(g).addClass("cloned").prependTo(this.$stage)}},{filter:["width",
"items","settings"],run:function(){for(var b=this.settings.rtl?1:-1,a=this._clones.length+this._items.length,c=-1,e=0,g=0,h=[];++c<a;)e=h[c-1]||0,g=this._widths[this.relative(c)]+this.settings.margin,h.push(e+g*b);this._coordinates=h}},{filter:["width","items","settings"],run:function(){var b=this.settings.stagePadding,a=this._coordinates,b={width:Math.ceil(Math.abs(a[a.length-1]))+2*b,"padding-left":b||"","padding-right":b||""};this.$stage.css(b)}},{filter:["width","items","settings"],run:function(b){var a=
this._coordinates.length,c=!this.settings.autoWidth,e=this.$stage.children();if(c&&b.items.merge)for(;a--;)b.css.width=this._widths[this.relative(a)],e.eq(a).css(b.css);else c&&(b.css.width=b.items.width,e.css(b.css))}},{filter:["items"],run:function(){1>this._coordinates.length&&this.$stage.removeAttr("style")}},{filter:["width","items","settings"],run:function(b){b.current=b.current?this.$stage.children().index(b.current):0;b.current=Math.max(this.minimum(),Math.min(this.maximum(),b.current));this.reset(b.current)}},
{filter:["position"],run:function(){this.animate(this.coordinates(this._current))}},{filter:["width","position","items","settings"],run:function(){var b=this.settings.rtl?1:-1,a=2*this.settings.stagePadding,c=this.coordinates(this.current())+a,e=c+this.width()*b,g,h,k=[],l,m;l=0;for(m=this._coordinates.length;l<m;l++)g=this._coordinates[l-1]||0,h=Math.abs(this._coordinates[l])+a*b,(this.op(g,"<=",c)&&this.op(g,">",e)||this.op(h,"<",c)&&this.op(h,">",e))&&k.push(l);this.$stage.children(".active").removeClass("active");
this.$stage.children(":eq("+k.join("), :eq(")+")").addClass("active");this.$stage.children(".center").removeClass("center");this.settings.center&&this.$stage.children().eq(this.current()).addClass("center")}}];a.prototype.initializeStage=function(){this.$stage=this.$element.find("."+this.settings.stageClass);this.$stage.length||(this.$element.addClass(this.options.loadingClass),this.$stage=c("<"+this.settings.stageElement+">",{"class":this.settings.stageClass}).wrap(c("<div/>",{"class":this.settings.stageOuterClass})),
this.$element.append(this.$stage.parent()))};a.prototype.initializeItems=function(){var b=this.$element.find(".owl-item");b.length?(this._items=b.get().map(function(b){return c(b)}),this._mergers=this._items.map(function(){return 1}),this.refresh()):(this.replace(this.$element.children().not(this.$stage.parent())),this.isVisible()?this.refresh():this.invalidate("width"),this.$element.removeClass(this.options.loadingClass).addClass(this.options.loadedClass))};a.prototype.initialize=function(){this.enter("initializing");
this.trigger("initialize");this.$element.toggleClass(this.settings.rtlClass,this.settings.rtl);if(this.settings.autoWidth&&!this.is("pre-loading")){var b,a;b=this.$element.find("img");a=this.$element.children(this.settings.nestedItemSelector?"."+this.settings.nestedItemSelector:m).width();b.length&&0>=a&&this.preloadAutoWidthImages(b)}this.initializeStage();this.initializeItems();this.registerEventHandlers();this.leave("initializing");this.trigger("initialized")};a.prototype.isVisible=function(){return this.settings.checkVisibility?
this.$element.is(":visible"):!0};a.prototype.setup=function(){var b=this.viewport(),a=this.options.responsive,f=-1,e=null;a?(c.each(a,function(a){a<=b&&a>f&&(f=Number(a))}),e=c.extend({},this.options,a[f]),"function"===typeof e.stagePadding&&(e.stagePadding=e.stagePadding()),delete e.responsive,e.responsiveClass&&this.$element.attr("class",this.$element.attr("class").replace(new RegExp("("+this.options.responsiveClass+"-)\\S+\\s","g"),"$1"+f))):e=c.extend({},this.options);this.trigger("change",{property:{name:"settings",
value:e}});this._breakpoint=f;this.settings=e;this.invalidate("settings");this.trigger("changed",{property:{name:"settings",value:this.settings}})};a.prototype.optionsLogic=function(){this.settings.autoWidth&&(this.settings.stagePadding=!1,this.settings.merge=!1)};a.prototype.prepare=function(b){var a=this.trigger("prepare",{content:b});a.data||(a.data=c("<"+this.settings.itemElement+"/>").addClass(this.options.itemClass).append(b));this.trigger("prepared",{content:a.data});return a.data};a.prototype.update=
function(){for(var b=0,a=this._pipe.length,f=c.proxy(function(b){return this[b]},this._invalidated),e={};b<a;)(this._invalidated.all||0<c.grep(this._pipe[b].filter,f).length)&&this._pipe[b].run(e),b++;this._invalidated={};!this.is("valid")&&this.enter("valid")};a.prototype.width=function(b){b=b||a.Width.Default;switch(b){case a.Width.Inner:case a.Width.Outer:return this._width;default:return this._width-2*this.settings.stagePadding+this.settings.margin}};a.prototype.refresh=function(){this.enter("refreshing");
this.trigger("refresh");this.setup();this.optionsLogic();this.$element.addClass(this.options.refreshClass);this.update();this.$element.removeClass(this.options.refreshClass);this.leave("refreshing");this.trigger("refreshed")};a.prototype.onThrottledResize=function(){l.clearTimeout(this.resizeTimer);this.resizeTimer=l.setTimeout(this._handlers.onResize,this.settings.responsiveRefreshRate)};a.prototype.onResize=function(){if(!this._items.length||this._width===this.$element.width()||!this.isVisible())return!1;
this.enter("resizing");if(this.trigger("resize").isDefaultPrevented())return this.leave("resizing"),!1;this.invalidate("width");this.refresh();this.leave("resizing");this.trigger("resized")};a.prototype.registerEventHandlers=function(){if(c.support.transition)this.$stage.on(c.support.transition.end+".owl.core",c.proxy(this.onTransitionEnd,this));if(!1!==this.settings.responsive)this.on(l,"resize",this._handlers.onThrottledResize);this.settings.mouseDrag&&(this.$element.addClass(this.options.dragClass),
this.$stage.on("mousedown.owl.core",c.proxy(this.onDragStart,this)),this.$stage.on("dragstart.owl.core selectstart.owl.core",function(){return!1}));this.settings.touchDrag&&(this.$stage.on("touchstart.owl.core",c.proxy(this.onDragStart,this)),this.$stage.on("touchcancel.owl.core",c.proxy(this.onDragEnd,this)))};a.prototype.onDragStart=function(b){var a=null;3!==b.which&&(c.support.transform?(a=this.$stage.css("transform").replace(/.*\(|\)| /g,"").split(","),a={x:a[16===a.length?12:4],y:a[16===a.length?
13:5]}):(a=this.$stage.position(),a={x:this.settings.rtl?a.left+this.$stage.width()-this.width()+this.settings.margin:a.left,y:a.top}),this.is("animating")&&(c.support.transform?this.animate(a.x):this.$stage.stop(),this.invalidate("position")),this.$element.toggleClass(this.options.grabClass,"mousedown"===b.type),this.speed(0),this._drag.time=(new Date).getTime(),this._drag.target=c(b.target),this._drag.stage.start=a,this._drag.stage.current=a,this._drag.pointer=this.pointer(b),c(n).on("mouseup.owl.core touchend.owl.core",
c.proxy(this.onDragEnd,this)),c(n).one("mousemove.owl.core touchmove.owl.core",c.proxy(function(b){var a=this.difference(this._drag.pointer,this.pointer(b));c(n).on("mousemove.owl.core touchmove.owl.core",c.proxy(this.onDragMove,this));Math.abs(a.x)<Math.abs(a.y)&&this.is("valid")||(b.preventDefault(),this.enter("dragging"),this.trigger("drag"))},this)))};a.prototype.onDragMove=function(b){var a=null,c=null,e=null,e=this.difference(this._drag.pointer,this.pointer(b)),g=this.difference(this._drag.stage.start,
e);this.is("dragging")&&(b.preventDefault(),this.settings.loop?(a=this.coordinates(this.minimum()),c=this.coordinates(this.maximum()+1)-a,g.x=((g.x-a)%c+c)%c+a):(a=this.settings.rtl?this.coordinates(this.maximum()):this.coordinates(this.minimum()),c=this.settings.rtl?this.coordinates(this.minimum()):this.coordinates(this.maximum()),e=this.settings.pullDrag?-1*e.x/5:0,g.x=Math.max(Math.min(g.x,a+e),c+e)),this._drag.stage.current=g,this.animate(g.x))};a.prototype.onDragEnd=function(b){b=this.difference(this._drag.pointer,
this.pointer(b));var a=this._drag.stage.current,f=0<b.x^this.settings.rtl?"left":"right";c(n).off(".owl.core");this.$element.removeClass(this.options.grabClass);if(0!==b.x&&this.is("dragging")||!this.is("valid"))if(this.speed(this.settings.dragEndSpeed||this.settings.smartSpeed),this.current(this.closest(a.x,0!==b.x?f:this._drag.direction)),this.invalidate("position"),this.update(),this._drag.direction=f,3<Math.abs(b.x)||300<(new Date).getTime()-this._drag.time)this._drag.target.one("click.owl.core",
function(){return!1});this.is("dragging")&&(this.leave("dragging"),this.trigger("dragged"))};a.prototype.closest=function(b,a){var f=-1,e=this.width(),g=this.coordinates();this.settings.freeDrag||c.each(g,c.proxy(function(c,k){"left"===a&&b>k-30&&b<k+30?f=c:"right"===a&&b>k-e-30&&b<k-e+30?f=c+1:this.op(b,"<",k)&&this.op(b,">",g[c+1]!==m?g[c+1]:k-e)&&(f="left"===a?c+1:c);return-1===f},this));this.settings.loop||(this.op(b,">",g[this.minimum()])?f=b=this.minimum():this.op(b,"<",g[this.maximum()])&&
(f=b=this.maximum()));return f};a.prototype.animate=function(b){var a=0<this.speed();this.is("animating")&&this.onTransitionEnd();a&&(this.enter("animating"),this.trigger("translate"));c.support.transform3d&&c.support.transition?this.$stage.css({transform:"translate3d("+b+"px,0px,0px)",transition:this.speed()/1E3+"s"+(this.settings.slideTransition?" "+this.settings.slideTransition:"")}):a?this.$stage.animate({left:b+"px"},this.speed(),this.settings.fallbackEasing,c.proxy(this.onTransitionEnd,this)):
this.$stage.css({left:b+"px"})};a.prototype.is=function(b){return this._states.current[b]&&0<this._states.current[b]};a.prototype.current=function(b){if(b===m)return this._current;if(0===this._items.length)return m;b=this.normalize(b);if(this._current!==b){var a=this.trigger("change",{property:{name:"position",value:b}});a.data!==m&&(b=this.normalize(a.data));this._current=b;this.invalidate("position");this.trigger("changed",{property:{name:"position",value:this._current}})}return this._current};
a.prototype.invalidate=function(b){"string"===c.type(b)&&(this._invalidated[b]=!0,this.is("valid")&&this.leave("valid"));return c.map(this._invalidated,function(b,a){return a})};a.prototype.reset=function(b){b=this.normalize(b);b!==m&&(this._speed=0,this._current=b,this.suppress(["translate","translated"]),this.animate(this.coordinates(b)),this.release(["translate","translated"]))};a.prototype.normalize=function(b,a){var c=this._items.length,e=a?0:this._clones.length;if(!this.isNumeric(b)||1>c)b=
m;else if(0>b||b>=c+e)b=((b-e/2)%c+c)%c+e/2;return b};a.prototype.relative=function(b){b-=this._clones.length/2;return this.normalize(b,!0)};a.prototype.maximum=function(b){var a=this.settings,c=this._coordinates.length,e;if(a.loop)c=this._clones.length/2+this._items.length-1;else if(a.autoWidth||a.merge){if(a=this._items.length)for(c=this._items[--a].width(),e=this.$element.width();a--&&!(c+=this._items[a].width()+this.settings.margin,c>e););c=a+1}else c=a.center?this._items.length-1:this._items.length-
a.items;b&&(c-=this._clones.length/2);return Math.max(c,0)};a.prototype.minimum=function(b){return b?0:this._clones.length/2};a.prototype.items=function(b){if(b===m)return this._items.slice();b=this.normalize(b,!0);return this._items[b]};a.prototype.mergers=function(b){if(b===m)return this._mergers.slice();b=this.normalize(b,!0);return this._mergers[b]};a.prototype.clones=function(b){var a=this._clones.length/2,f=a+this._items.length;return b===m?c.map(this._clones,function(b,c){return 0===c%2?f+
c/2:a-(c+1)/2}):c.map(this._clones,function(c,g){return c===b?0===g%2?f+g/2:a-(g+1)/2:null})};a.prototype.speed=function(b){b!==m&&(this._speed=b);return this._speed};a.prototype.coordinates=function(b){var a=1,f=b-1;if(b===m)return c.map(this._coordinates,c.proxy(function(b,a){return this.coordinates(a)},this));this.settings.center?(this.settings.rtl&&(a=-1,f=b+1),b=this._coordinates[b],b+=(this.width()-b+(this._coordinates[f]||0))/2*a):b=this._coordinates[f]||0;return b=Math.ceil(b)};a.prototype.duration=
function(b,a,c){return 0===c?0:Math.min(Math.max(Math.abs(a-b),1),6)*Math.abs(c||this.settings.smartSpeed)};a.prototype.to=function(b,a){var c=this.current(),e=null,g=b-this.relative(c),e=(0<g)-(0>g),h=this._items.length,k=this.minimum(),l=this.maximum();this.settings.loop?(!this.settings.rewind&&Math.abs(g)>h/2&&(g+=-1*e*h),b=c+g,e=((b-k)%h+h)%h+k,e!==b&&e-g<=l&&0<e-g&&(c=e-g,b=e,this.reset(c))):this.settings.rewind?(l+=1,b=(b%l+l)%l):b=Math.max(k,Math.min(l,b));this.speed(this.duration(c,b,a));
this.current(b);this.isVisible()&&this.update()};a.prototype.next=function(b){b=b||!1;this.to(this.relative(this.current())+1,b)};a.prototype.prev=function(b){b=b||!1;this.to(this.relative(this.current())-1,b)};a.prototype.onTransitionEnd=function(b){if(b!==m&&(b.stopPropagation(),(b.target||b.srcElement||b.originalTarget)!==this.$stage.get(0)))return!1;this.leave("animating");this.trigger("translated")};a.prototype.viewport=function(){var b;this.options.responsiveBaseElement!==l?b=c(this.options.responsiveBaseElement).width():
l.innerWidth?b=l.innerWidth:n.documentElement&&n.documentElement.clientWidth?b=n.documentElement.clientWidth:console.warn("Can not detect viewport width.");return b};a.prototype.replace=function(b){this.$stage.empty();this._items=[];b&&(b=b instanceof jQuery?b:c(b));this.settings.nestedItemSelector&&(b=b.find("."+this.settings.nestedItemSelector));b.filter(function(){return 1===this.nodeType}).each(c.proxy(function(b,a){a=this.prepare(a);this.$stage.append(a);this._items.push(a);this._mergers.push(1*
a.find("[data-merge]").addBack("[data-merge]").attr("data-merge")||1)},this));this.reset(this.isNumeric(this.settings.startPosition)?this.settings.startPosition:0);this.invalidate("items")};a.prototype.add=function(b,a){var f=this.relative(this._current);a=a===m?this._items.length:this.normalize(a,!0);b=b instanceof jQuery?b:c(b);this.trigger("add",{content:b,position:a});b=this.prepare(b);0===this._items.length||a===this._items.length?(0===this._items.length&&this.$stage.append(b),0!==this._items.length&&
this._items[a-1].after(b),this._items.push(b),this._mergers.push(1*b.find("[data-merge]").addBack("[data-merge]").attr("data-merge")||1)):(this._items[a].before(b),this._items.splice(a,0,b),this._mergers.splice(a,0,1*b.find("[data-merge]").addBack("[data-merge]").attr("data-merge")||1));this._items[f]&&this.reset(this._items[f].index());this.invalidate("items");this.trigger("added",{content:b,position:a})};a.prototype.remove=function(b){b=this.normalize(b,!0);b!==m&&(this.trigger("remove",{content:this._items[b],
position:b}),this._items[b].remove(),this._items.splice(b,1),this._mergers.splice(b,1),this.invalidate("items"),this.trigger("removed",{content:null,position:b}))};a.prototype.preloadAutoWidthImages=function(b){b.each(c.proxy(function(b,a){this.enter("pre-loading");a=c(a);c(new Image).one("load",c.proxy(function(b){a.attr("src",b.target.src);a.css("opacity",1);this.leave("pre-loading");this.is("pre-loading")||this.is("initializing")||this.refresh()},this)).attr("src",a.attr("src")||a.attr("data-src")||
a.attr("data-src-retina"))},this))};a.prototype.destroy=function(){this.$element.off(".owl.core");this.$stage.off(".owl.core");c(n).off(".owl.core");!1!==this.settings.responsive&&(l.clearTimeout(this.resizeTimer),this.off(l,"resize",this._handlers.onThrottledResize));for(var b in this._plugins)this._plugins[b].destroy();this.$stage.children(".cloned").remove();this.$stage.unwrap();this.$stage.children().contents().unwrap();this.$stage.children().unwrap();this.$stage.remove();this.$element.removeClass(this.options.refreshClass).removeClass(this.options.loadingClass).removeClass(this.options.loadedClass).removeClass(this.options.rtlClass).removeClass(this.options.dragClass).removeClass(this.options.grabClass).attr("class",
this.$element.attr("class").replace(new RegExp(this.options.responsiveClass+"-\\S+\\s","g"),"")).removeData("owl.carousel")};a.prototype.op=function(b,a,c){var e=this.settings.rtl;switch(a){case "<":return e?b>c:b<c;case ">":return e?b<c:b>c;case ">=":return e?b<=c:b>=c;case "<=":return e?b>=c:b<=c}};a.prototype.on=function(b,a,c,e){b.addEventListener?b.addEventListener(a,c,e):b.attachEvent&&b.attachEvent("on"+a,c)};a.prototype.off=function(b,a,c,e){b.removeEventListener?b.removeEventListener(a,c,
e):b.detachEvent&&b.detachEvent("on"+a,c)};a.prototype.trigger=function(b,d,f,e,g){e={item:{count:this._items.length,index:this.current()}};g=c.camelCase(c.grep(["on",b,f],function(b){return b}).join("-").toLowerCase());var h=c.Event([b,"owl",f||"carousel"].join(".").toLowerCase(),c.extend({relatedTarget:this},e,d));this._supress[b]||(c.each(this._plugins,function(b,a){if(a.onTrigger)a.onTrigger(h)}),this.register({type:a.Type.Event,name:b}),this.$element.trigger(h),this.settings&&"function"===typeof this.settings[g]&&
this.settings[g].call(this,h));return h};a.prototype.enter=function(b){c.each([b].concat(this._states.tags[b]||[]),c.proxy(function(b,a){this._states.current[a]===m&&(this._states.current[a]=0);this._states.current[a]++},this))};a.prototype.leave=function(b){c.each([b].concat(this._states.tags[b]||[]),c.proxy(function(b,a){this._states.current[a]--},this))};a.prototype.register=function(b){if(b.type===a.Type.Event){if(c.event.special[b.name]||(c.event.special[b.name]={}),!c.event.special[b.name].owl){var d=
c.event.special[b.name]._default;c.event.special[b.name]._default=function(b){return!d||!d.apply||b.namespace&&-1!==b.namespace.indexOf("owl")?b.namespace&&-1<b.namespace.indexOf("owl"):d.apply(this,arguments)};c.event.special[b.name].owl=!0}}else b.type===a.Type.State&&(this._states.tags[b.name]=this._states.tags[b.name]?this._states.tags[b.name].concat(b.tags):b.tags,this._states.tags[b.name]=c.grep(this._states.tags[b.name],c.proxy(function(a,d){return c.inArray(a,this._states.tags[b.name])===
d},this)))};a.prototype.suppress=function(b){c.each(b,c.proxy(function(b,a){this._supress[a]=!0},this))};a.prototype.release=function(b){c.each(b,c.proxy(function(b,a){delete this._supress[a]},this))};a.prototype.pointer=function(b){var a={x:null,y:null};b=b.originalEvent||b||l.event;b=b.touches&&b.touches.length?b.touches[0]:b.changedTouches&&b.changedTouches.length?b.changedTouches[0]:b;b.pageX?(a.x=b.pageX,a.y=b.pageY):(a.x=b.clientX,a.y=b.clientY);return a};a.prototype.isNumeric=function(b){return!isNaN(parseFloat(b))};
a.prototype.difference=function(b,a){return{x:b.x-a.x,y:b.y-a.y}};c.fn.owlCarousel=function(b){var d=Array.prototype.slice.call(arguments,1);return this.each(function(){var f=c(this),e=f.data("owl.carousel");e||(e=new a(this,"object"==typeof b&&b),f.data("owl.carousel",e),c.each("next prev to destroy refresh replace add remove".split(" "),function(b,d){e.register({type:a.Type.Event,name:d});e.$element.on(d+".owl.carousel.core",c.proxy(function(b){b.namespace&&b.relatedTarget!==this&&(this.suppress([d]),
e[d].apply(this,[].slice.call(arguments,1)),this.release([d]))},e))}));"string"==typeof b&&"_"!==b.charAt(0)&&e[b].apply(e,d)})};c.fn.owlCarousel.Constructor=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._visible=this._interval=null;this._handlers={"initialized.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.autoRefresh&&this.watch()},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this._core.$element.on(this._handlers)};a.Defaults={autoRefresh:!0,autoRefreshInterval:500};a.prototype.watch=function(){this._interval||(this._visible=this._core.isVisible(),this._interval=l.setInterval(c.proxy(this.refresh,
this),this._core.settings.autoRefreshInterval))};a.prototype.refresh=function(){this._core.isVisible()!==this._visible&&(this._visible=!this._visible,this._core.$element.toggleClass("owl-hidden",!this._visible),this._visible&&this._core.invalidate("width")&&this._core.refresh())};a.prototype.destroy=function(){var b,a;l.clearInterval(this._interval);for(b in this._handlers)this._core.$element.off(b,this._handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!=typeof this[a]&&(this[a]=null)};
c.fn.owlCarousel.Constructor.Plugins.AutoRefresh=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._loaded=[];this._handlers={"initialized.owl.carousel change.owl.carousel resized.owl.carousel":c.proxy(function(b){if(b.namespace&&this._core.settings&&this._core.settings.lazyLoad&&(b.property&&"position"==b.property.name||"initialized"==b.type)){var a=this._core.settings,e=a.center&&Math.ceil(a.items/2)||a.items,g=a.center&&-1*e||0;b=(b.property&&b.property.value!==m?b.property.value:this._core.current())+g;var h=this._core.clones().length,
k=c.proxy(function(b,a){this.load(a)},this);0<a.lazyLoadEager&&(e+=a.lazyLoadEager,a.loop&&(b-=a.lazyLoadEager,e++));for(;g++<e;)this.load(h/2+this._core.relative(b)),h&&c.each(this._core.clones(this._core.relative(b)),k),b++}},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this._core.$element.on(this._handlers)};a.Defaults={lazyLoad:!1,lazyLoadEager:0};a.prototype.load=function(b){var a=(b=this._core.$stage.children().eq(b))&&b.find(".owl-lazy");!a||-1<c.inArray(b.get(0),this._loaded)||
(a.each(c.proxy(function(b,a){var d=c(a),h,k=1<l.devicePixelRatio&&d.attr("data-src-retina")||d.attr("data-src")||d.attr("data-srcset");this._core.trigger("load",{element:d,url:k},"lazy");d.is("img")?d.one("load.owl.lazy",c.proxy(function(){d.css("opacity",1);this._core.trigger("loaded",{element:d,url:k},"lazy")},this)).attr("src",k):d.is("source")?d.one("load.owl.lazy",c.proxy(function(){this._core.trigger("loaded",{element:d,url:k},"lazy")},this)).attr("srcset",k):(h=new Image,h.onload=c.proxy(function(){d.css({"background-image":'url("'+
k+'")',opacity:"1"});this._core.trigger("loaded",{element:d,url:k},"lazy")},this),h.src=k)},this)),this._loaded.push(b.get(0)))};a.prototype.destroy=function(){var b,a;for(b in this.handlers)this._core.$element.off(b,this.handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!=typeof this[a]&&(this[a]=null)};c.fn.owlCarousel.Constructor.Plugins.Lazy=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._previousHeight=null;this._handlers={"initialized.owl.carousel refreshed.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.autoHeight&&this.update()},this),"changed.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.autoHeight&&"position"===b.property.name&&this.update()},this),"loaded.owl.lazy":c.proxy(function(b){b.namespace&&this._core.settings.autoHeight&&b.element.closest("."+this._core.settings.itemClass).index()===
this._core.current()&&this.update()},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this._core.$element.on(this._handlers);this._intervalId=null;var d=this;c(l).on("load",function(){d._core.settings.autoHeight&&d.update()});c(l).resize(function(){d._core.settings.autoHeight&&(null!=d._intervalId&&clearTimeout(d._intervalId),d._intervalId=setTimeout(function(){d.update()},250))})};a.Defaults={autoHeight:!1,autoHeightClass:"owl-height"};a.prototype.update=function(){var b=this._core._current,
a=b+this._core.settings.items,f=this._core.settings.lazyLoad,b=this._core.$stage.children().toArray().slice(b,a),e=[],a=0;c.each(b,function(b,a){e.push(c(a).height())});a=Math.max.apply(null,e);1>=a&&f&&this._previousHeight&&(a=this._previousHeight);this._previousHeight=a;this._core.$stage.parent().height(a).addClass(this._core.settings.autoHeightClass)};a.prototype.destroy=function(){var b,a;for(b in this._handlers)this._core.$element.off(b,this._handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!==
typeof this[a]&&(this[a]=null)};c.fn.owlCarousel.Constructor.Plugins.AutoHeight=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._videos={};this._playing=null;this._handlers={"initialized.owl.carousel":c.proxy(function(b){b.namespace&&this._core.register({type:"state",name:"playing",tags:["interacting"]})},this),"resize.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.video&&this.isInFullScreen()&&b.preventDefault()},this),"refreshed.owl.carousel":c.proxy(function(b){b.namespace&&this._core.is("resizing")&&this._core.$stage.find(".cloned .owl-video-frame").remove()},
this),"changed.owl.carousel":c.proxy(function(b){b.namespace&&"position"===b.property.name&&this._playing&&this.stop()},this),"prepared.owl.carousel":c.proxy(function(b){if(b.namespace){var a=c(b.content).find(".owl-video");a.length&&(a.css("display","none"),this.fetch(a,c(b.content)))}},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this._core.$element.on(this._handlers);this._core.$element.on("click.owl.video",".owl-video-play-icon",c.proxy(function(b){this.play(b)},this))};
a.Defaults={video:!1,videoHeight:!1,videoWidth:!1};a.prototype.fetch=function(b,a){var c=b.attr("data-vimeo-id")?"vimeo":b.attr("data-vzaar-id")?"vzaar":"youtube",e=b.attr("data-vimeo-id")||b.attr("data-youtube-id")||b.attr("data-vzaar-id"),g=b.attr("data-width")||this._core.settings.videoWidth,h=b.attr("data-height")||this._core.settings.videoHeight,k=b.attr("href");if(k){e=k.match(/(http:|https:|)\/\/(player.|www.|app.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com|be\-nocookie\.com)|vzaar\.com)\/(video\/|videos\/|embed\/|channels\/.+\/|groups\/.+\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(\&\S+)?/);
if(-1<e[3].indexOf("youtu"))c="youtube";else if(-1<e[3].indexOf("vimeo"))c="vimeo";else if(-1<e[3].indexOf("vzaar"))c="vzaar";else throw Error("Video URL not supported.");e=e[6]}else throw Error("Missing video URL.");this._videos[k]={type:c,id:e,width:g,height:h};a.attr("data-video",k);this.thumbnail(b,this._videos[k])};a.prototype.thumbnail=function(b,a){var f,e,g=a.width&&a.height?"width:"+a.width+"px;height:"+a.height+"px;":"",h=b.find("img"),k="src",l="",m=this._core.settings,n=function(a){f=
m.lazyLoad?c("<div/>",{"class":"owl-video-tn "+l,srcType:a}):c("<div/>",{"class":"owl-video-tn",style:"opacity:1;background-image:url("+a+")"});b.after(f);b.after('<div class="owl-video-play-icon"></div>')};b.wrap(c("<div/>",{"class":"owl-video-wrapper",style:g}));this._core.settings.lazyLoad&&(k="data-src",l="owl-lazy");if(h.length)return n(h.attr(k)),h.remove(),!1;"youtube"===a.type?(e="//img.youtube.com/vi/"+a.id+"/hqdefault.jpg",n(e)):"vimeo"===a.type?c.ajax({type:"GET",url:"//vimeo.com/api/v2/video/"+
a.id+".json",jsonp:"callback",dataType:"jsonp",success:function(b){e=b[0].thumbnail_large;n(e)}}):"vzaar"===a.type&&c.ajax({type:"GET",url:"//vzaar.com/api/videos/"+a.id+".json",jsonp:"callback",dataType:"jsonp",success:function(b){e=b.framegrab_url;n(e)}})};a.prototype.stop=function(){this._core.trigger("stop",null,"video");this._playing.find(".owl-video-frame").remove();this._playing.removeClass("owl-video-playing");this._playing=null;this._core.leave("playing");this._core.trigger("stopped",null,
"video")};a.prototype.play=function(b){b=c(b.target).closest("."+this._core.settings.itemClass);var a=this._videos[b.attr("data-video")],f=a.width||"100%",e=a.height||this._core.$stage.height(),g;this._playing||(this._core.enter("playing"),this._core.trigger("play",null,"video"),b=this._core.items(this._core.relative(b.index())),this._core.reset(b.index()),g=c('<iframe frameborder="0" allowfullscreen mozallowfullscreen webkitAllowFullScreen ></iframe>'),g.attr("height",e),g.attr("width",f),"youtube"===
a.type?g.attr("src","//www.youtube.com/embed/"+a.id+"?autoplay=1&rel=0&v="+a.id):"vimeo"===a.type?g.attr("src","//player.vimeo.com/video/"+a.id+"?autoplay=1"):"vzaar"===a.type&&g.attr("src","//view.vzaar.com/"+a.id+"/player?autoplay=true"),c(g).wrap('<div class="owl-video-frame" />').insertAfter(b.find(".owl-video")),this._playing=b.addClass("owl-video-playing"))};a.prototype.isInFullScreen=function(){var b=n.fullscreenElement||n.mozFullScreenElement||n.webkitFullscreenElement;return b&&c(b).parent().hasClass("owl-video-frame")};
a.prototype.destroy=function(){var b,a;this._core.$element.off("click.owl.video");for(b in this._handlers)this._core.$element.off(b,this._handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!=typeof this[a]&&(this[a]=null)};c.fn.owlCarousel.Constructor.Plugins.Video=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this.core=b;this.core.options=c.extend({},a.Defaults,this.core.options);this.swapping=!0;this.next=this.previous=m;this.handlers={"change.owl.carousel":c.proxy(function(b){b.namespace&&"position"==b.property.name&&(this.previous=this.core.current(),this.next=b.property.value)},this),"drag.owl.carousel dragged.owl.carousel translated.owl.carousel":c.proxy(function(b){b.namespace&&(this.swapping="translated"==b.type)},this),"translate.owl.carousel":c.proxy(function(b){b.namespace&&
this.swapping&&(this.core.options.animateOut||this.core.options.animateIn)&&this.swap()},this)};this.core.$element.on(this.handlers)};a.Defaults={animateOut:!1,animateIn:!1};a.prototype.swap=function(){if(1===this.core.settings.items&&c.support.animation&&c.support.transition){this.core.speed(0);var b,a=c.proxy(this.clear,this),f=this.core.$stage.children().eq(this.previous),e=this.core.$stage.children().eq(this.next),g=this.core.settings.animateIn,h=this.core.settings.animateOut;this.core.current()!==
this.previous&&(h&&(b=this.core.coordinates(this.previous)-this.core.coordinates(this.next),f.one(c.support.animation.end,a).css({left:b+"px"}).addClass("animated owl-animated-out").addClass(h)),g&&e.one(c.support.animation.end,a).addClass("animated owl-animated-in").addClass(g))}};a.prototype.clear=function(b){c(b.target).css({left:""}).removeClass("animated owl-animated-out owl-animated-in").removeClass(this.core.settings.animateIn).removeClass(this.core.settings.animateOut);this.core.onTransitionEnd()};
a.prototype.destroy=function(){var b,a;for(b in this.handlers)this.core.$element.off(b,this.handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!=typeof this[a]&&(this[a]=null)};c.fn.owlCarousel.Constructor.Plugins.Animate=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._call=null;this._timeout=this._time=0;this._paused=!0;this._handlers={"changed.owl.carousel":c.proxy(function(b){b.namespace&&"settings"===b.property.name?this._core.settings.autoplay?this.play():this.stop():b.namespace&&"position"===b.property.name&&this._paused&&(this._time=0)},this),"initialized.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.autoplay&&this.play()},this),"play.owl.autoplay":c.proxy(function(b,a,c){b.namespace&&
this.play(a,c)},this),"stop.owl.autoplay":c.proxy(function(b){b.namespace&&this.stop()},this),"mouseover.owl.autoplay":c.proxy(function(){this._core.settings.autoplayHoverPause&&this._core.is("rotating")&&this.pause()},this),"mouseleave.owl.autoplay":c.proxy(function(){this._core.settings.autoplayHoverPause&&this._core.is("rotating")&&this.play()},this),"touchstart.owl.core":c.proxy(function(){this._core.settings.autoplayHoverPause&&this._core.is("rotating")&&this.pause()},this),"touchend.owl.core":c.proxy(function(){this._core.settings.autoplayHoverPause&&
this.play()},this)};this._core.$element.on(this._handlers);this._core.options=c.extend({},a.Defaults,this._core.options)};a.Defaults={autoplay:!1,autoplayTimeout:5E3,autoplayHoverPause:!1,autoplaySpeed:!1};a.prototype._next=function(b){this._call=l.setTimeout(c.proxy(this._next,this,b),this._timeout*(Math.round(this.read()/this._timeout)+1)-this.read());this._core.is("interacting")||n.hidden||this._core.next(b||this._core.settings.autoplaySpeed)};a.prototype.read=function(){return(new Date).getTime()-
this._time};a.prototype.play=function(b,a){var f;this._core.is("rotating")||this._core.enter("rotating");b=b||this._core.settings.autoplayTimeout;f=Math.min(this._time%(this._timeout||b),b);this._paused?(this._time=this.read(),this._paused=!1):l.clearTimeout(this._call);this._time+=this.read()%b-f;this._timeout=b;this._call=l.setTimeout(c.proxy(this._next,this,a),b-f)};a.prototype.stop=function(){this._core.is("rotating")&&(this._time=0,this._paused=!0,l.clearTimeout(this._call),this._core.leave("rotating"))};
a.prototype.pause=function(){this._core.is("rotating")&&!this._paused&&(this._time=this.read(),this._paused=!0,l.clearTimeout(this._call))};a.prototype.destroy=function(){var b,a;this.stop();for(b in this._handlers)this._core.$element.off(b,this._handlers[b]);for(a in Object.getOwnPropertyNames(this))"function"!=typeof this[a]&&(this[a]=null)};c.fn.owlCarousel.Constructor.Plugins.autoplay=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._initialized=!1;this._pages=[];this._controls={};this._templates=[];this.$element=this._core.$element;this._overrides={next:this._core.next,prev:this._core.prev,to:this._core.to};this._handlers={"prepared.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.dotsData&&this._templates.push('<div class="'+this._core.settings.dotClass+'">'+c(b.content).find("[data-dot]").addBack("[data-dot]").attr("data-dot")+"</div>")},this),"added.owl.carousel":c.proxy(function(b){b.namespace&&
this._core.settings.dotsData&&this._templates.splice(b.position,0,this._templates.pop())},this),"remove.owl.carousel":c.proxy(function(b){b.namespace&&this._core.settings.dotsData&&this._templates.splice(b.position,1)},this),"changed.owl.carousel":c.proxy(function(b){b.namespace&&"position"==b.property.name&&this.draw()},this),"initialized.owl.carousel":c.proxy(function(b){b.namespace&&!this._initialized&&(this._core.trigger("initialize",null,"navigation"),this.initialize(),this.update(),this.draw(),
this._initialized=!0,this._core.trigger("initialized",null,"navigation"))},this),"refreshed.owl.carousel":c.proxy(function(b){b.namespace&&this._initialized&&(this._core.trigger("refresh",null,"navigation"),this.update(),this.draw(),this._core.trigger("refreshed",null,"navigation"))},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this.$element.on(this._handlers)};a.Defaults={nav:!1,navText:['<span aria-label="Previous">&#x2039;</span>','<span aria-label="Next">&#x203a;</span>'],
navSpeed:!1,navElement:'button type="button" role="presentation"',navContainer:!1,navContainerClass:"owl-nav",navClass:["owl-prev","owl-next"],slideBy:1,dotClass:"owl-dot",dotsClass:"owl-dots",dots:!0,dotsEach:!1,dotsData:!1,dotsSpeed:!1,dotsContainer:!1};a.prototype.initialize=function(){var b,a=this._core.settings;this._controls.$relative=(a.navContainer?c(a.navContainer):c("<div>").addClass(a.navContainerClass).appendTo(this.$element)).addClass("disabled");this._controls.$previous=c("<"+a.navElement+
">").addClass(a.navClass[0]).html(a.navText[0]).prependTo(this._controls.$relative).on("click",c.proxy(function(b){this.prev(a.navSpeed)},this));this._controls.$next=c("<"+a.navElement+">").addClass(a.navClass[1]).html(a.navText[1]).appendTo(this._controls.$relative).on("click",c.proxy(function(b){this.next(a.navSpeed)},this));a.dotsData||(this._templates=[c('<button role="button">').addClass(a.dotClass).append(c("<span>")).prop("outerHTML")]);this._controls.$absolute=(a.dotsContainer?c(a.dotsContainer):
c("<div>").addClass(a.dotsClass).appendTo(this.$element)).addClass("disabled");this._controls.$absolute.on("click","button",c.proxy(function(b){var e=c(b.target).parent().is(this._controls.$absolute)?c(b.target).index():c(b.target).parent().index();b.preventDefault();this.to(e,a.dotsSpeed)},this));for(b in this._overrides)this._core[b]=c.proxy(this[b],this)};a.prototype.destroy=function(){var b,a,c,e,g;g=this._core.settings;for(b in this._handlers)this.$element.off(b,this._handlers[b]);for(a in this._controls)"$relative"===
a&&g.navContainer?this._controls[a].html(""):this._controls[a].remove();for(e in this.overides)this._core[e]=this._overrides[e];for(c in Object.getOwnPropertyNames(this))"function"!=typeof this[c]&&(this[c]=null)};a.prototype.update=function(){var b,a,c,e=this._core.clones().length/2,g=e+this._core.items().length,h=this._core.maximum(!0);b=this._core.settings;var k=b.center||b.autoWidth||b.dotsData?1:b.dotsEach||b.items;"page"!==b.slideBy&&(b.slideBy=Math.min(b.slideBy,b.items));if(b.dots||"page"==
b.slideBy)for(this._pages=[],b=e,c=a=0;b<g;b++){if(a>=k||0===a){this._pages.push({start:Math.min(h,b-e),end:b-e+k-1});if(Math.min(h,b-e)===h)break;a=0;++c}a+=this._core.mergers(this._core.relative(b))}};a.prototype.draw=function(){var b,a=this._core.settings;b=this._core.items().length<=a.items;var f=this._core.relative(this._core.current()),e=a.loop||a.rewind;this._controls.$relative.toggleClass("disabled",!a.nav||b);a.nav&&(this._controls.$previous.toggleClass("disabled",!e&&f<=this._core.minimum(!0)),
this._controls.$next.toggleClass("disabled",!e&&f>=this._core.maximum(!0)));this._controls.$absolute.toggleClass("disabled",!a.dots||b);a.dots&&(b=this._pages.length-this._controls.$absolute.children().length,a.dotsData&&0!==b?this._controls.$absolute.html(this._templates.join("")):0<b?this._controls.$absolute.append(Array(b+1).join(this._templates[0])):0>b&&this._controls.$absolute.children().slice(b).remove(),this._controls.$absolute.find(".active").removeClass("active"),this._controls.$absolute.children().eq(c.inArray(this.current(),
this._pages)).addClass("active"))};a.prototype.onTrigger=function(b){var a=this._core.settings;b.page={index:c.inArray(this.current(),this._pages),count:this._pages.length,size:a&&(a.center||a.autoWidth||a.dotsData?1:a.dotsEach||a.items)}};a.prototype.current=function(){var b=this._core.relative(this._core.current());return c.grep(this._pages,c.proxy(function(a,c){return a.start<=b&&a.end>=b},this)).pop()};a.prototype.getPosition=function(b){var a,f;f=this._core.settings;"page"==f.slideBy?(a=c.inArray(this.current(),
this._pages),f=this._pages.length,b?++a:--a,a=this._pages[(a%f+f)%f].start):(a=this._core.relative(this._core.current()),this._core.items(),b?a+=f.slideBy:a-=f.slideBy);return a};a.prototype.next=function(a){c.proxy(this._overrides.to,this._core)(this.getPosition(!0),a)};a.prototype.prev=function(a){c.proxy(this._overrides.to,this._core)(this.getPosition(!1),a)};a.prototype.to=function(a,d,f){!f&&this._pages.length?(f=this._pages.length,c.proxy(this._overrides.to,this._core)(this._pages[(a%f+f)%f].start,
d)):c.proxy(this._overrides.to,this._core)(a,d)};c.fn.owlCarousel.Constructor.Plugins.Navigation=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){var a=function(b){this._core=b;this._hashes={};this.$element=this._core.$element;this._handlers={"initialized.owl.carousel":c.proxy(function(a){a.namespace&&"URLHash"===this._core.settings.startPosition&&c(l).trigger("hashchange.owl.navigation")},this),"prepared.owl.carousel":c.proxy(function(a){if(a.namespace){var b=c(a.content).find("[data-hash]").addBack("[data-hash]").attr("data-hash");b&&(this._hashes[b]=a.content)}},this),"changed.owl.carousel":c.proxy(function(a){if(a.namespace&&
"position"===a.property.name){var b=this._core.items(this._core.relative(this._core.current()));(a=c.map(this._hashes,function(a,c){return a===b?c:null}).join())&&l.location.hash.slice(1)!==a&&(l.location.hash=a)}},this)};this._core.options=c.extend({},a.Defaults,this._core.options);this.$element.on(this._handlers);c(l).on("hashchange.owl.navigation",c.proxy(function(a){a=l.location.hash.substring(1);var b=this._core.$stage.children();a=this._hashes[a]&&b.index(this._hashes[a]);a!==m&&a!==this._core.current()&&
this._core.to(this._core.relative(a),!1,!0)},this))};a.Defaults={URLhashListener:!1};a.prototype.destroy=function(){var a,d;c(l).off("hashchange.owl.navigation");for(a in this._handlers)this._core.$element.off(a,this._handlers[a]);for(d in Object.getOwnPropertyNames(this))"function"!=typeof this[d]&&(this[d]=null)};c.fn.owlCarousel.Constructor.Plugins.Hash=a})(window.Zepto||window.jQuery,window,document);
(function(c,l,n,m){function a(a,f){var h=!1,k=a.charAt(0).toUpperCase()+a.slice(1);c.each((a+" "+d.join(k+" ")+k).split(" "),function(a,c){if(b[c]!==m)return h=f?c:!0,!1});return h}var b=c("<support>").get(0).style,d=["Webkit","Moz","O","ms"];l={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd",transition:"transitionend"};n={WebkitAnimation:"webkitAnimationEnd",MozAnimation:"animationend",OAnimation:"oAnimationEnd",animation:"animationend"};var f={csstransforms:function(){return!!a("transform")},
csstransforms3d:function(){return!!a("perspective")},csstransitions:function(){return!!a("transition")},cssanimations:function(){return!!a("animation")}};f.csstransitions()&&(c.support.transition=new String(a("transition",!0)),c.support.transition.end=l[c.support.transition]);f.cssanimations()&&(c.support.animation=new String(a("animation",!0)),c.support.animation.end=n[c.support.animation]);f.csstransforms()&&(c.support.transform=new String(a("transform",!0)),c.support.transform3d=f.csstransforms3d())})(window.Zepto||
window.jQuery,window,document);
